#!/usr/bin/env bash
# Install librouting_core (+ Valhalla Nebenlibs) into Flutter Android jniLibs.
#
# Prerequisites (Valhalla-linked build):
#   source data/routing/dist/valhalla-build/prefix-android-arm64-v8a/aetherride-env.sh
#   cd mobile/packages/routing_core/native
#   cargo build --release --features valhalla --target aarch64-linux-android
#
# Usage:
#   ./scripts/routing/install-android-jni.sh              # arm64-v8a + Valhalla deps
#   ./scripts/routing/install-android-jni.sh --graph-only # no protobuf (offline_graph .so)
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
ABI="${ANDROID_ABI:-arm64-v8a}"
GRAPH_ONLY=0
for arg in "$@"; do
  case "$arg" in
    --graph-only) GRAPH_ONLY=1 ;;
    arm64-v8a|armeabi-v7a|x86_64|x86) ABI="$arg" ;;
    *)
      echo "Unknown arg: $arg" >&2
      exit 1
      ;;
  esac
done

case "$ABI" in
  arm64-v8a) RUST_TARGET=aarch64-linux-android; NDK_TRIPLE=aarch64-linux-android ;;
  armeabi-v7a) RUST_TARGET=armv7-linux-androideabi; NDK_TRIPLE=arm-linux-androideabi ;;
  x86_64) RUST_TARGET=x86_64-linux-android; NDK_TRIPLE=x86_64-linux-android ;;
  x86) RUST_TARGET=i686-linux-android; NDK_TRIPLE=i686-linux-android ;;
  *) echo "Unsupported ABI: $ABI" >&2; exit 1 ;;
esac

NATIVE="$ROOT/mobile/packages/routing_core/native"
SRC="$NATIVE/target/$RUST_TARGET/release/librouting_core.so"
JNI="$ROOT/mobile/android/app/src/main/jniLibs/$ABI"
NDK="${ANDROID_NDK_HOME:-${ANDROID_NDK:-}}"
# Fallbacks when Gradle/preBuild does not export ANDROID_NDK_HOME
if [[ -z "$NDK" || ! -d "$NDK" ]]; then
  if [[ -f "$ROOT/mobile/android/local.properties" ]]; then
    sdk_dir=$(grep -E '^sdk\.dir=' "$ROOT/mobile/android/local.properties" | head -1 | cut -d= -f2- | tr -d '\r')
    if [[ -n "$sdk_dir" && -d "$sdk_dir/ndk" ]]; then
      NDK=$(ls -d "$sdk_dir"/ndk/*/ 2>/dev/null | sort -V | tail -1 | sed 's:/*$::')
    fi
  fi
fi
if [[ -z "$NDK" || ! -d "$NDK" ]]; then
  for cand in "$HOME/Android/Sdk/ndk"/*; do
    [[ -d "$cand" ]] || continue
    NDK="$cand"
  done
fi

if [[ ! -f "$SRC" ]]; then
  echo "Missing $SRC" >&2
  echo "Build first, e.g.:" >&2
  if [[ "$GRAPH_ONLY" -eq 1 ]]; then
    echo "  cd $NATIVE && cargo build --release --target $RUST_TARGET" >&2
  else
    echo "  source …/aetherride-env.sh && cd $NATIVE && cargo build --release --features valhalla --target $RUST_TARGET" >&2
  fi
  exit 1
fi

if [[ "$GRAPH_ONLY" -eq 0 ]] && command -v readelf >/dev/null; then
  if ! readelf -d "$SRC" 2>/dev/null | grep -q 'libprotobuf'; then
    GRAPH_ONLY=1
    echo "librouting_core.so has no libprotobuf NEEDED — graph-only install"
  fi
fi

mkdir -p "$JNI"
install -m 0644 "$SRC" "$JNI/librouting_core.so"
echo "Installed librouting_core.so → $JNI ($(du -h "$JNI/librouting_core.so" | cut -f1))"
if command -v readelf >/dev/null; then
  align=$(readelf -W -l "$JNI/librouting_core.so" | awk '/LOAD/ {print $NF; exit}')
  echo "ELF LOAD align=$align (Android 16 KB pages need 0x4000)"
  if [[ "$align" != "0x4000" && "$align" != "16384" ]]; then
    echo "WARN: librouting_core.so is not 16 KB aligned. Rebuild with -Wl,-z,max-page-size=16384 (build.rs)." >&2
  fi
fi

if [[ "$GRAPH_ONLY" -eq 1 ]]; then
  rm -f "$JNI/libprotobuf.so"
  echo "graph-only: skipped libprotobuf.so"
else
  PB_LIB="${PROTOBUF_LIB_DIR:-$HOME/tools/protobuf-android-$ABI/lib}"
  if [[ ! -f "$PB_LIB/libprotobuf.so" ]]; then
    # fall back to arm64 tools path used by build-valhalla-android.sh
    PB_LIB="${PROTOBUF_LIB_DIR:-$HOME/tools/protobuf-android-arm64-v8a/lib}"
  fi
  if [[ ! -f "$PB_LIB/libprotobuf.so" ]]; then
    echo "Missing libprotobuf.so (set PROTOBUF_LIB_DIR). Use --graph-only if Valhalla is not linked." >&2
    exit 1
  fi
  install -m 0644 "$PB_LIB/libprotobuf.so" "$JNI/libprotobuf.so"
  echo "Installed libprotobuf.so ($(du -h "$JNI/libprotobuf.so" | cut -f1))"
fi

if [[ -z "$NDK" || ! -d "$NDK" ]]; then
  echo "WARN: ANDROID_NDK_HOME unset — libc++_shared.so not copied (Flutter may still provide it)." >&2
else
  CXX_SHARED="$NDK/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/$NDK_TRIPLE/libc++_shared.so"
  if [[ -f "$CXX_SHARED" ]]; then
    install -m 0644 "$CXX_SHARED" "$JNI/libc++_shared.so"
    echo "Installed libc++_shared.so ($(du -h "$JNI/libc++_shared.so" | cut -f1))"
  else
    echo "WARN: $CXX_SHARED not found" >&2
  fi
fi

# Marker for gradle / diagnostics
cat > "$JNI/README.txt" <<EOF
Generated by scripts/routing/install-android-jni.sh — do not commit .so files.
ABI=$ABI RUST_TARGET=$RUST_TARGET GRAPH_ONLY=$GRAPH_ONLY
EOF

echo "Done. Flutter loads via DynamicLibrary.open('librouting_core.so')."
