# Flutter / Play / native keep rules for release minify.
-keep class io.flutter.app.** { *; }
-keep class io.flutter.plugin.** { *; }
-keep class io.flutter.util.** { *; }
-keep class io.flutter.view.** { *; }
-keep class io.flutter.** { *; }
-keep class io.flutter.plugins.** { *; }

# MapLibre / JNI
-keep class org.maplibre.** { *; }
-keep class com.mapbox.** { *; }
-dontwarn org.maplibre.**
-dontwarn com.mapbox.**

# FlutterBluePlus / BLE
-keep class com.signify.hue.** { *; }
-dontwarn com.google.android.gms.**

# Flutter engine references Play Store Deferred Components APIs optionally
# (FlutterPlayStoreSplitApplication / PlayStoreDeferredComponentManager).
# We don't use dynamic feature modules / the Play Core split-install library,
# so these classes are never loaded at runtime — safe to silence, otherwise
# R8 fails the Release build with "Missing class" errors (AGP 9 / R8 strict
# mode). Rules as generated by AGP into
# build/app/outputs/mapping/release/missing_rules.txt.
-dontwarn com.google.android.play.core.splitcompat.SplitCompatApplication
-dontwarn com.google.android.play.core.splitinstall.SplitInstallException
-dontwarn com.google.android.play.core.splitinstall.SplitInstallManager
-dontwarn com.google.android.play.core.splitinstall.SplitInstallManagerFactory
-dontwarn com.google.android.play.core.splitinstall.SplitInstallRequest$Builder
-dontwarn com.google.android.play.core.splitinstall.SplitInstallRequest
-dontwarn com.google.android.play.core.splitinstall.SplitInstallSessionState
-dontwarn com.google.android.play.core.splitinstall.SplitInstallStateUpdatedListener
-dontwarn com.google.android.play.core.tasks.OnFailureListener
-dontwarn com.google.android.play.core.tasks.OnSuccessListener
-dontwarn com.google.android.play.core.tasks.Task

# HUD media — NotificationListenerService must stay findable by the OS.
-keep class com.aetherride.aetherride_mobile.HudMediaListenerService { *; }
-keep class com.aetherride.aetherride_mobile.HudMediaPlugin { *; }

# Keep native method names used by MethodChannels / FFI.
-keepclasseswithmembernames class * {
    native <methods>;
}
