/**
 * FlowLine chrome marks — same 24px line language as Touren/Garage glyphs.
 * Two-color files (#9CA3AF + #FF6A00). Tabs and filled chips use the mask
 * (`current`) so the silhouette follows currentColor.
 */
export const CHROME_MARKS = [
  "hof",
  "karte",
  "platz",
  "shop",
  "search",
  "locate",
  "download",
  "filter",
  "layers",
  "merken",
  "heat",
  "flag",
  "recent",
  "undo",
  "redo",
  "play",
  "offline",
  "photo",
  "elevation",
  "share",
  "shield",
  "calendar",
  "users",
  "phone",
  "watch",
  "user",
  "star",
  "mail",
  "swap",
  "bell",
  "nav",
  "split",
  "check",
  "care",
  "stimmen",
  "lock",
  "add",
  "meet",
  "lang",
  "cloud",
  "crown",
  "hint",
  "pause",
  "enter",
  "bluetooth",
  "trash",
  "link",
  "send",
  "compass",
  "file",
  "gear",
  "loop",
  "copy",
] as const;

export type ChromeMarkName = (typeof CHROME_MARKS)[number];

export const CHROME_MARK_SRC: Record<ChromeMarkName, string> = {
  hof: "/chrome/glyph-hof.svg",
  karte: "/chrome/glyph-karte.svg",
  platz: "/tours/glyph-mappe.svg",
  shop: "/chrome/glyph-shop.svg",
  search: "/chrome/glyph-search.svg",
  locate: "/chrome/glyph-locate.svg",
  download: "/chrome/glyph-download.svg",
  filter: "/chrome/glyph-filter.svg",
  layers: "/chrome/glyph-layers.svg",
  merken: "/chrome/glyph-merken.svg",
  heat: "/chrome/glyph-heat.svg",
  flag: "/chrome/glyph-flag.svg",
  recent: "/chrome/glyph-recent.svg",
  undo: "/chrome/glyph-undo.svg",
  redo: "/chrome/glyph-redo.svg",
  play: "/chrome/glyph-play.svg",
  offline: "/weather/offline.svg",
  photo: "/garage/glyph-photo.svg",
  elevation: "/tours/glyph-elevation.svg",
  share: "/chrome/glyph-share.svg",
  shield: "/chrome/glyph-shield.svg",
  calendar: "/chrome/glyph-calendar.svg",
  users: "/chrome/glyph-users.svg",
  phone: "/chrome/glyph-phone.svg",
  watch: "/chrome/glyph-watch.svg",
  user: "/chrome/glyph-user.svg",
  star: "/chrome/glyph-star.svg",
  mail: "/chrome/glyph-mail.svg",
  swap: "/chrome/glyph-swap.svg",
  bell: "/chrome/glyph-bell.svg",
  nav: "/chrome/glyph-nav.svg",
  split: "/chrome/glyph-split.svg",
  check: "/garage/glyph-ready.svg",
  care: "/garage/glyph-care.svg",
  stimmen: "/tours/glyph-stimmen.svg",
  lock: "/garage/glyph-lock.svg",
  add: "/garage/glyph-add.svg",
  meet: "/tours/glyph-meet.svg",
  lang: "/chrome/glyph-lang.svg",
  cloud: "/chrome/glyph-cloud.svg",
  crown: "/chrome/glyph-crown.svg",
  hint: "/chrome/glyph-hint.svg",
  pause: "/chrome/glyph-pause.svg",
  enter: "/chrome/glyph-enter.svg",
  bluetooth: "/chrome/glyph-bluetooth.svg",
  trash: "/chrome/glyph-trash.svg",
  link: "/chrome/glyph-link.svg",
  send: "/chrome/glyph-send.svg",
  compass: "/chrome/glyph-compass.svg",
  file: "/chrome/glyph-file.svg",
  gear: "/chrome/glyph-gear.svg",
  loop: "/tours/glyph-loop.svg",
  copy: "/chrome/glyph-copy.svg",
};
