import type { CatalogManufacturer, ComponentSlot } from "@/types/garage";

/** Gemeinsames Enduro-Kit (SRAM) — fehlende Slots bleiben leer → INSUFFICIENT_DATA */
const SRAM_ENDURO_KIT: Partial<Record<ComponentSlot, string>> = {
  headset: "cm-cane-creek-zs44-zs56",
  stem: "cm-renthal-apex-35",
  handlebar: "cm-renthal-fatbar-35",
  grips: "cm-odey-grips",
  saddle: "cm-sdg-belair",
  front_hub: "cm-dt-350-boost-front",
  rear_hub: "cm-dt-350-boost-rear-xd",
  front_rim: "cm-dt-xm1700-rim-front",
  rear_rim: "cm-dt-xm1700-rim-rear",
  tire_front: "cm-maxxis-assegai-29-25",
  tire_rear: "cm-maxxis-dhr2-29-24",
  cassette: "cm-sram-x0-cassette-xd",
  chain: "cm-sram-gx-chain",
  crankset: "cm-sram-x0-crank-dub",
  chainring: "cm-sram-x0-chainring-32",
  rear_derailleur: "cm-sram-x0-rd",
  shifter: "cm-sram-pod-controller",
  bottom_bracket: "cm-sram-dub-bsa73",
  brake_front: "cm-sram-code-rsc-front",
  brake_rear: "cm-sram-code-rsc-rear",
  rotor_front: "cm-sram-hs2-200-front",
  rotor_rear: "cm-sram-hs2-180-rear",
  brake_pads_front: "cm-sram-organic-pads",
  brake_pads_rear: "cm-sram-organic-pads-rear",
  pedals: "cm-ht-components-pedals",
};

const SHIMANO_ENDURO_KIT: Partial<Record<ComponentSlot, string>> = {
  headset: "cm-cane-creek-zs44-zs56",
  stem: "cm-renthal-apex-35",
  handlebar: "cm-renthal-fatbar-35",
  grips: "cm-odey-grips",
  saddle: "cm-sdg-belair",
  front_hub: "cm-dt-350-boost-front-cl",
  rear_hub: "cm-dt-350-boost-rear-ms-cl",
  front_rim: "cm-dt-xm1700-rim-front",
  rear_rim: "cm-dt-xm1700-rim-rear",
  tire_front: "cm-continental-kryptotal-f-29",
  tire_rear: "cm-continental-kryptotal-r-29",
  cassette: "cm-shimano-xt-cassette-ms",
  chain: "cm-shimano-cn-m8100",
  crankset: "cm-shimano-xt-crank-m8120",
  chainring: "cm-shimano-xt-chainring-32",
  rear_derailleur: "cm-shimano-xt-rd-m8100",
  shifter: "cm-shimano-xt-shifter-m8100",
  bottom_bracket: "cm-shimano-bb-mt800",
  brake_front: "cm-shimano-xt-m8120-front",
  brake_rear: "cm-shimano-xt-m8120-rear",
  rotor_front: "cm-shimano-rt86-203-front",
  rotor_rear: "cm-shimano-rt86-180-rear",
  pedals: "cm-ht-components-pedals",
};

/**
 * OEM-Bike-Katalog F-GAR-001 — DACH-Enduro-Schwerpunkt (G-4 Slice).
 * Spec-Ziel ≥3000 Modelle: hier kuratierter Seed, skalierbar.
 */
export const BIKE_CATALOG: CatalogManufacturer[] = [
  {
    id: "mfr-transition",
    name: "Transition",
    bikes: [
      {
        id: "cat-transition-spire-2024",
        name: "Spire",
        year: 2024,
        frameSizeOptions: ["S", "M", "L", "XL"],
        category: "mtb_enduro",
        travelFrontMm: 170,
        travelRearMm: 170,
        wheelSizeFront: "29",
        wheelSizeRear: "29",
        isEbike: false,
        weightKgApprox: 15.8,
        oemComponents: {
          ...SRAM_ENDURO_KIT,
          frame: "cm-transition-spire-frame",
          fork: "cm-fox-36-factory-170",
          rear_shock: "cm-fox-float-x2-20565",
          seatpost: "cm-oneup-v3-dropper-31-6",
        },
        frameAttributes: [],
        sourceUrl: "https://www.transitionbikes.com/",
      },
    ],
  },
  {
    id: "mfr-yt",
    name: "YT Industries",
    bikes: [
      {
        id: "cat-yt-capra-2024",
        name: "Capra MX Uncaged 9",
        year: 2024,
        frameSizeOptions: ["S", "M", "L", "XL"],
        category: "mtb_enduro",
        travelFrontMm: 170,
        travelRearMm: 170,
        wheelSizeFront: "29",
        wheelSizeRear: "29",
        isEbike: false,
        weightKgApprox: 15.2,
        oemComponents: {
          ...SRAM_ENDURO_KIT,
          frame: "cm-yt-capra-frame",
          fork: "cm-fox-38-factory-170",
          rear_shock: "cm-fox-float-x-20565",
          seatpost: "cm-oneup-v3-dropper-31-6",
          tire_front: "cm-maxxis-minion-dhf-29-25",
        },
        frameAttributes: [],
        sourceUrl: "https://www.yt-industries.com/",
      },
    ],
  },
  {
    id: "mfr-propain",
    name: "Propain",
    bikes: [
      {
        id: "cat-propain-tyee-2024",
        name: "Tyee AL",
        year: 2024,
        frameSizeOptions: ["S", "M", "L", "XL"],
        category: "mtb_enduro",
        travelFrontMm: 170,
        travelRearMm: 160,
        wheelSizeFront: "29",
        wheelSizeRear: "29",
        isEbike: false,
        weightKgApprox: 15.5,
        oemComponents: {
          ...SRAM_ENDURO_KIT,
          frame: "cm-propain-tyee-frame",
          fork: "cm-rockshox-zeb-170",
          rear_shock: "cm-rockshox-vivid-23065",
          seatpost: "cm-oneup-v3-dropper-31-6",
          brake_front: "cm-magura-mt7-front",
          brake_rear: "cm-magura-mt7-rear",
        },
        frameAttributes: [],
        sourceUrl: "https://www.propain-bikes.com/",
      },
    ],
  },
  {
    id: "mfr-canyon",
    name: "Canyon",
    bikes: [
      {
        id: "cat-canyon-spectralon-2024",
        name: "Spectral:ON CF 8",
        year: 2024,
        frameSizeOptions: ["S", "M", "L", "XL"],
        category: "emtb",
        travelFrontMm: 160,
        travelRearMm: 150,
        wheelSizeFront: "29",
        wheelSizeRear: "29",
        isEbike: true,
        weightKgApprox: 23.5,
        oemComponents: {
          ...SRAM_ENDURO_KIT,
          frame: "cm-canyon-spectralon-cf-frame",
          fork: "cm-rockshox-lyrik-160",
          rear_shock: "cm-rockshox-superdeluxe-23065",
          seatpost: "cm-oneup-v3-dropper-34-9",
          motor: "cm-bosch-cx-gen5",
          battery: "cm-bosch-powertube-800",
          display: "cm-bosch-kiox-300",
        },
        frameAttributes: [],
        sourceUrl: "https://www.canyon.com/",
      },
      {
        id: "cat-canyon-spectral-cf8-2024",
        name: "Spectral CF 8",
        year: 2024,
        frameSizeOptions: ["S", "M", "L", "XL"],
        category: "mtb_am",
        travelFrontMm: 150,
        travelRearMm: 140,
        wheelSizeFront: "29",
        wheelSizeRear: "29",
        isEbike: false,
        weightKgApprox: 14.2,
        oemComponents: {
          ...SRAM_ENDURO_KIT,
          frame: "cm-canyon-spectral-cf-frame",
          fork: "cm-rockshox-lyrik-160",
          rear_shock: "cm-fox-float-x-21055",
          seatpost: "cm-oneup-v3-dropper-30-9",
        },
        frameAttributes: [],
        sourceUrl: "https://www.canyon.com/",
      },
    ],
  },
  {
    id: "mfr-cube",
    name: "Cube",
    bikes: [
      {
        id: "cat-cube-stereo-one44-2024",
        name: "Stereo ONE44 C:62",
        year: 2024,
        frameSizeOptions: ["S", "M", "L", "XL"],
        category: "mtb_am",
        travelFrontMm: 140,
        travelRearMm: 140,
        wheelSizeFront: "29",
        wheelSizeRear: "29",
        isEbike: false,
        weightKgApprox: 13.8,
        oemComponents: {
          ...SHIMANO_ENDURO_KIT,
          frame: "cm-cube-stereo-one44-frame",
          fork: "cm-rockshox-lyrik-160",
          rear_shock: "cm-fox-float-x-21055",
          seatpost: "cm-oneup-v3-dropper-30-9",
        },
        frameAttributes: [],
        sourceUrl: "https://www.cube.eu/",
      },
      {
        id: "cat-cube-stereo-hybrid-160-2024",
        name: "Stereo Hybrid 160 HPC Race",
        year: 2024,
        frameSizeOptions: ["S", "M", "L", "XL"],
        category: "emtb",
        travelFrontMm: 170,
        travelRearMm: 160,
        wheelSizeFront: "29",
        wheelSizeRear: "29",
        isEbike: true,
        weightKgApprox: 24.2,
        oemComponents: {
          ...SHIMANO_ENDURO_KIT,
          frame: "cm-cube-stereo-hybrid-frame",
          fork: "cm-fox-38-factory-170",
          rear_shock: "cm-fox-float-x2-23065",
          seatpost: "cm-oneup-v3-dropper-30-9",
          motor: "cm-bosch-cx-gen5",
          battery: "cm-bosch-powertube-800",
          display: "cm-bosch-kiox-300",
        },
        frameAttributes: [],
        sourceUrl: "https://www.cube.eu/",
      },
    ],
  },
  {
    id: "mfr-rose",
    name: "Rose",
    bikes: [
      {
        id: "cat-rose-root-miller-2024",
        name: "Root Miller 3",
        year: 2024,
        frameSizeOptions: ["S", "M", "L", "XL"],
        category: "mtb_enduro",
        travelFrontMm: 170,
        travelRearMm: 160,
        wheelSizeFront: "29",
        wheelSizeRear: "29",
        isEbike: false,
        weightKgApprox: 15.0,
        oemComponents: {
          ...SRAM_ENDURO_KIT,
          frame: "cm-rose-root-miller-frame",
          fork: "cm-ohlins-rxf38-170",
          rear_shock: "cm-fox-float-x2-20565",
          seatpost: "cm-oneup-v3-dropper-31-6",
          tire_front: "cm-continental-kryptotal-f-29",
          tire_rear: "cm-continental-kryptotal-r-29",
        },
        frameAttributes: [],
        sourceUrl: "https://www.rosebikes.de/",
      },
    ],
  },
  {
    id: "mfr-specialized",
    name: "Specialized",
    bikes: [
      {
        id: "cat-specialized-enduro-2024",
        name: "Enduro Comp",
        year: 2024,
        frameSizeOptions: ["S2", "S3", "S4", "S5"],
        category: "mtb_enduro",
        travelFrontMm: 170,
        travelRearMm: 170,
        wheelSizeFront: "29",
        wheelSizeRear: "29",
        isEbike: false,
        weightKgApprox: 15.6,
        oemComponents: {
          ...SRAM_ENDURO_KIT,
          frame: "cm-specialized-enduro-frame",
          fork: "cm-fox-38-factory-170",
          rear_shock: "cm-fox-float-x2-20565",
          seatpost: "cm-oneup-v3-dropper-34-9",
        },
        frameAttributes: [],
        sourceUrl: "https://www.specialized.com/",
      },
      {
        id: "cat-specialized-diverge-2023",
        name: "Diverge Carbon",
        year: 2023,
        frameSizeOptions: ["49", "52", "54", "56", "58"],
        category: "gravel",
        travelFrontMm: 0,
        travelRearMm: 0,
        wheelSizeFront: "700c",
        wheelSizeRear: "700c",
        isEbike: false,
        weightKgApprox: 9.2,
        oemComponents: {
          frame: "cm-specialized-diverge-frame",
          tire_front: "cm-pathfinder-pro-700-42",
          tire_rear: "cm-pathfinder-pro-700-42",
        },
        frameAttributes: [],
        sourceUrl: "https://www.specialized.com/",
      },
    ],
  },
  {
    id: "mfr-trek",
    name: "Trek",
    bikes: [
      {
        id: "cat-trek-slash-8-2024",
        name: "Slash 8",
        year: 2024,
        frameSizeOptions: ["S", "M", "L", "XL"],
        category: "mtb_enduro",
        travelFrontMm: 170,
        travelRearMm: 170,
        wheelSizeFront: "29",
        wheelSizeRear: "29",
        isEbike: false,
        weightKgApprox: 15.9,
        oemComponents: {
          ...SRAM_ENDURO_KIT,
          frame: "cm-trek-slash-frame",
          fork: "cm-rockshox-zeb-170",
          rear_shock: "cm-rockshox-vivid-23065",
          seatpost: "cm-oneup-v3-dropper-34-9",
          tire_front: "cm-maxxis-minion-dhf-29-25",
        },
        frameAttributes: [],
        sourceUrl: "https://www.trekbikes.com/",
      },
    ],
  },
  {
    id: "mfr-santa-cruz",
    name: "Santa Cruz",
    bikes: [
      {
        id: "cat-santa-cruz-hightower-2024",
        name: "Hightower C",
        year: 2024,
        frameSizeOptions: ["S", "M", "L", "XL"],
        category: "mtb_am",
        travelFrontMm: 150,
        travelRearMm: 145,
        wheelSizeFront: "29",
        wheelSizeRear: "29",
        isEbike: false,
        weightKgApprox: 14.5,
        oemComponents: {
          ...SRAM_ENDURO_KIT,
          frame: "cm-santa-cruz-hightower-frame",
          fork: "cm-fox-36-factory-170",
          rear_shock: "cm-fox-float-x-20565",
          seatpost: "cm-fox-transfer-31-6",
          tire_front: "cm-schwalbe-magic-mary-29",
          tire_rear: "cm-maxxis-aggressor-29-25",
        },
        frameAttributes: [],
        sourceUrl: "https://www.santacruzbicycles.com/",
      },
    ],
  },
  {
    id: "mfr-commencal",
    name: "Commencal",
    bikes: [
      {
        id: "cat-commencal-meta-am-2024",
        name: "Meta AM 29",
        year: 2024,
        frameSizeOptions: ["S", "M", "L", "XL"],
        category: "mtb_enduro",
        travelFrontMm: 170,
        travelRearMm: 170,
        wheelSizeFront: "29",
        wheelSizeRear: "29",
        isEbike: false,
        weightKgApprox: 15.4,
        oemComponents: {
          ...SRAM_ENDURO_KIT,
          frame: "cm-commencal-meta-am-frame",
          fork: "cm-rockshox-zeb-170",
          rear_shock: "cm-rockshox-vivid-23065",
          seatpost: "cm-bikeyoke-revive-31-6",
          brake_front: "cm-hope-tech4-v4-front",
          brake_rear: "cm-hope-tech4-v4-rear",
          rotor_front: "cm-hope-floating-200-front",
          rotor_rear: "cm-hope-floating-180-rear",
          front_hub: "cm-dt-240-boost-front-6b",
          rear_hub: "cm-dt-240-boost-rear-xd-6b",
          tire_front: "cm-schwalbe-magic-mary-29",
          tire_rear: "cm-schwalbe-big-betty-29",
        },
        frameAttributes: [],
        sourceUrl: "https://www.commencal.com/",
      },
    ],
  },
  {
    id: "mfr-orbea",
    name: "Orbea",
    bikes: [
      {
        id: "cat-orbea-rallon-2024",
        name: "Rallon M10",
        year: 2024,
        frameSizeOptions: ["S", "M", "L", "XL"],
        category: "mtb_enduro",
        travelFrontMm: 170,
        travelRearMm: 160,
        wheelSizeFront: "29",
        wheelSizeRear: "29",
        isEbike: false,
        weightKgApprox: 15.1,
        oemComponents: {
          ...SRAM_ENDURO_KIT,
          frame: "cm-orbea-rallon-frame",
          fork: "cm-fox-38-factory-170",
          rear_shock: "cm-fox-dhx2-20565",
          seatpost: "cm-oneup-v3-dropper-31-6",
          brake_front: "cm-sram-maven-silver-front",
          brake_rear: "cm-sram-maven-silver-rear",
        },
        frameAttributes: [],
        sourceUrl: "https://www.orbea.com/",
      },
    ],
  },
  {
    id: "mfr-nukeproof",
    name: "Nukeproof",
    bikes: [
      {
        id: "cat-nukeproof-giga-2024",
        name: "Giga 290",
        year: 2024,
        frameSizeOptions: ["S", "M", "L", "XL"],
        category: "mtb_enduro",
        travelFrontMm: 180,
        travelRearMm: 170,
        wheelSizeFront: "29",
        wheelSizeRear: "29",
        isEbike: false,
        weightKgApprox: 16.0,
        oemComponents: {
          ...SRAM_ENDURO_KIT,
          frame: "cm-nukeproof-giga-frame",
          fork: "cm-rockshox-zeb-170",
          rear_shock: "cm-rockshox-vivid-23065",
          seatpost: "cm-bikeyoke-revive-31-6",
          rear_hub: "cm-i9-hydra-boost-rear-xd",
          front_hub: "cm-dt-240-boost-front-6b",
          brake_front: "cm-hope-tech4-v4-front",
          brake_rear: "cm-hope-tech4-v4-rear",
          rotor_front: "cm-hope-floating-200-front",
          rotor_rear: "cm-hope-floating-180-rear",
        },
        frameAttributes: [],
        sourceUrl: "https://nukeproof.com/",
      },
    ],
  },
  {
    id: "mfr-pivot",
    name: "Pivot",
    bikes: [
      {
        id: "cat-pivot-firebird-2024",
        name: "Firebird",
        year: 2024,
        frameSizeOptions: ["S", "M", "L", "XL"],
        category: "mtb_enduro",
        travelFrontMm: 170,
        travelRearMm: 165,
        wheelSizeFront: "29",
        wheelSizeRear: "29",
        isEbike: false,
        weightKgApprox: 15.3,
        oemComponents: {
          ...SRAM_ENDURO_KIT,
          frame: "cm-pivot-firebird-frame",
          fork: "cm-fox-38-factory-170",
          rear_shock: "cm-cane-creek-dbair-20565",
          seatpost: "cm-fox-transfer-31-6",
        },
        frameAttributes: [],
        sourceUrl: "https://www.pivotcycles.com/",
      },
    ],
  },
  {
    id: "mfr-forbidden",
    name: "Forbidden",
    bikes: [
      {
        id: "cat-forbidden-dreadnought-2024",
        name: "Dreadnought V2",
        year: 2024,
        frameSizeOptions: ["S1", "S2", "S3", "S4"],
        category: "mtb_enduro",
        travelFrontMm: 170,
        travelRearMm: 170,
        wheelSizeFront: "29",
        wheelSizeRear: "29",
        isEbike: false,
        weightKgApprox: 15.7,
        oemComponents: {
          ...SRAM_ENDURO_KIT,
          frame: "cm-forbidden-dreadnought-frame",
          fork: "cm-fox-38-factory-170",
          rear_shock: "cm-fox-dhx2-20565",
          seatpost: "cm-bikeyoke-revive-31-6",
          tire_front: "cm-maxxis-minion-dhf-29-25",
          tire_rear: "cm-maxxis-aggressor-29-25",
        },
        frameAttributes: [],
        sourceUrl: "https://www.forbiddenbike.com/",
      },
    ],
  },
];

export function findCatalogBike(id: string) {
  for (const m of BIKE_CATALOG) {
    const bike = m.bikes.find((b) => b.id === id);
    if (bike) return { manufacturer: m, bike };
  }
  return undefined;
}

export function listCatalogManufacturers() {
  return BIKE_CATALOG;
}

export function catalogStats() {
  const manufacturers = BIKE_CATALOG.length;
  const bikes = BIKE_CATALOG.reduce((n, m) => n + m.bikes.length, 0);
  const oemRefs = BIKE_CATALOG.reduce(
    (n, m) =>
      n +
      m.bikes.reduce(
        (bn, b) => bn + Object.keys(b.oemComponents ?? {}).length,
        0
      ),
    0
  );
  return { manufacturers, bikes, oemRefs };
}
