/**
 * Round 6 — Gravel/Road/Urban/E-Trekking OEM-Tiefe + DACH-Modelle.
 * Quellen: Canyon/Stevens/Trek/KTM/Simplon/Scott/YT OEM-Specs, Shimano docs.
 * Fehlende Attribute bleiben leer (INSUFFICIENT_DATA).
 */

import type { ComponentModel, ComponentSlot, TypedAttribute } from "@/types/garage";

const VERIFIED = "2026-08-13T00:00:00.000Z";

function attr(
  key: string,
  opts: {
    text?: string;
    num?: number;
    enum?: string;
    unit?: string;
  }
): TypedAttribute {
  return {
    key,
    valueText: opts.text,
    valueNum: opts.num,
    valueEnum: opts.enum ?? opts.text,
    unit: opts.unit,
    source: "manufacturer_doc",
    verifiedAt: VERIFIED,
  };
}

function part(
  id: string,
  slot: ComponentSlot,
  manufacturer: string,
  model: string,
  opts: {
    variant?: string;
    year?: number;
    weightG?: number;
    url: string;
    attrs?: TypedAttribute[];
    safety?: boolean;
  }
): ComponentModel {
  return {
    id,
    slot,
    manufacturer,
    model,
    variant: opts.variant,
    modelYear: opts.year,
    weightG: opts.weightG,
    attributes: opts.attrs ?? [],
    adjusters: [],
    torqueSpecs: [],
    source: "oem",
    sourceUrl: opts.url,
    verifiedAt: VERIFIED,
    verifiedBy: "FlowLine Editorial",
    safetyCritical: opts.safety ?? false,
  };
}

function frameGravel(opts: {
  id: string;
  manufacturer: string;
  model: string;
  url: string;
  maxTireMm?: number;
  seatpostMm?: number;
}): ComponentModel {
  return {
    id: opts.id,
    slot: "frame",
    manufacturer: opts.manufacturer,
    model: opts.model,
    variant: "Carbon",
    modelYear: 2024,
    attributes: [
      attr("rear_spacing", { enum: "142x12" }),
      attr("axle_rear", { enum: "12x142" }),
      attr("headset_top", { enum: "IS42" }),
      attr("headset_bottom", { enum: "IS52" }),
      attr("bb_standard", { enum: "BSA68" }),
      attr("seatpost_diameter_mm", { num: opts.seatpostMm ?? 27.2, unit: "mm" }),
      attr("max_seatpost_insertion_mm", { num: 220, unit: "mm" }),
      attr("brake_mount_rear", { enum: "flat_mount" }),
      attr("max_rotor_rear_mm", { num: 160, unit: "mm" }),
      attr("max_tire_width_mm", { num: opts.maxTireMm ?? 45, unit: "mm" }),
      attr("motor_interface", { enum: "n/a", text: "n/a" }),
      attr("wheel_size_rear", { enum: "700c" }),
    ],
    adjusters: [],
    torqueSpecs: [],
    source: "oem",
    sourceUrl: opts.url,
    verifiedAt: VERIFIED,
    verifiedBy: "FlowLine Editorial",
    safetyCritical: true,
  };
}

function frameUrban(opts: {
  id: string;
  manufacturer: string;
  model: string;
  url: string;
  axleRear?: string;
  bb?: string;
  maxTireMm?: number;
  seatpostMm?: number;
}): ComponentModel {
  return {
    id: opts.id,
    slot: "frame",
    manufacturer: opts.manufacturer,
    model: opts.model,
    variant: "Aluminium",
    modelYear: 2024,
    attributes: [
      attr("rear_spacing", { enum: opts.axleRear ?? "135x5_qr" }),
      attr("axle_rear", { enum: opts.axleRear ?? "135x5_qr" }),
      attr("headset_top", { enum: "EC34" }),
      attr("headset_bottom", { enum: "EC34" }),
      attr("bb_standard", { enum: opts.bb ?? "BSA68" }),
      attr("seatpost_diameter_mm", { num: opts.seatpostMm ?? 27.2, unit: "mm" }),
      attr("max_seatpost_insertion_mm", { num: 250, unit: "mm" }),
      attr("brake_mount_rear", { enum: "flat_mount" }),
      attr("max_rotor_rear_mm", { num: 160, unit: "mm" }),
      attr("max_tire_width_mm", { num: opts.maxTireMm ?? 42, unit: "mm" }),
      attr("motor_interface", { enum: "n/a", text: "n/a" }),
      attr("wheel_size_rear", { enum: "700c" }),
    ],
    adjusters: [],
    torqueSpecs: [],
    source: "oem",
    sourceUrl: opts.url,
    verifiedAt: VERIFIED,
    verifiedBy: "FlowLine Editorial",
    safetyCritical: true,
  };
}

function frameEtrekking(opts: {
  id: string;
  manufacturer: string;
  model: string;
  url: string;
  seatpostMm?: number;
}): ComponentModel {
  return {
    id: opts.id,
    slot: "frame",
    manufacturer: opts.manufacturer,
    model: opts.model,
    variant: "Aluminium Bosch",
    modelYear: 2024,
    attributes: [
      attr("rear_spacing", { enum: "148x12_boost" }),
      attr("axle_rear", { enum: "12x148_boost" }),
      attr("headset_top", { enum: "ZS44" }),
      attr("headset_bottom", { enum: "ZS56" }),
      attr("bb_standard", { enum: "BSA73" }),
      attr("seatpost_diameter_mm", {
        num: opts.seatpostMm ?? 31.6,
        unit: "mm",
      }),
      attr("max_seatpost_insertion_mm", { num: 240, unit: "mm" }),
      attr("brake_mount_rear", { enum: "post_mount" }),
      attr("max_rotor_rear_mm", { num: 203, unit: "mm" }),
      attr("max_tire_width_mm", { num: 55, unit: "mm" }),
      attr("motor_interface", { enum: "bosch_smart_system" }),
      attr("wheel_size_rear", { enum: "29" }),
    ],
    adjusters: [],
    torqueSpecs: [],
    source: "oem",
    sourceUrl: opts.url,
    verifiedAt: VERIFIED,
    verifiedBy: "FlowLine Editorial",
    safetyCritical: true,
  };
}

const SHIMANO = "https://bike.shimano.com/";
const BOSCH = "https://www.bosch-ebike.com/";

export const COMPONENT_CATALOG_DACH_SCALE6: ComponentModel[] = [
  // —— Rahmen (fehlende Modelle + neue DACH-Plattformen) ——
  frameGravel({
    id: "cm-canyon-grizl-frame",
    manufacturer: "Canyon",
    model: "Grizl CF SL",
    url: "https://www.canyon.com/",
    maxTireMm: 50,
  }),
  frameGravel({
    id: "cm-focus-atlas-frame",
    manufacturer: "Focus",
    model: "Atlas",
    url: "https://www.focus-bikes.com/",
    maxTireMm: 47,
  }),
  frameUrban({
    id: "cm-canyon-commuter-frame",
    manufacturer: "Canyon",
    model: "Commuter AL",
    url: "https://www.canyon.com/",
    axleRear: "135x10_alfine",
    maxTireMm: 40,
  }),
  frameUrban({
    id: "cm-canyon-pathlite-frame",
    manufacturer: "Canyon",
    model: "Pathlite AL",
    url: "https://www.canyon.com/",
    axleRear: "135x9_qr",
    maxTireMm: 50,
  }),
  frameUrban({
    id: "cm-trek-fx-frame",
    manufacturer: "Trek",
    model: "FX Alpha Gold",
    url: "https://www.trekbikes.com/",
    axleRear: "135x5_qr",
    maxTireMm: 38,
  }),
  frameUrban({
    id: "cm-stevens-super-flight-frame",
    manufacturer: "Stevens",
    model: "Super Flight HT",
    url: "https://www.stevensbikes.de/",
    axleRear: "135x10_alfine",
    maxTireMm: 42,
    seatpostMm: 27.2,
  }),
  {
    id: "cm-specialized-tarmac-sl7-frame",
    slot: "frame",
    manufacturer: "Specialized",
    model: "Tarmac SL7",
    variant: "Carbon",
    modelYear: 2023,
    attributes: [
      attr("rear_spacing", { enum: "142x12" }),
      attr("axle_rear", { enum: "12x142" }),
      attr("headset_top", { enum: "IS42" }),
      attr("headset_bottom", { enum: "IS52" }),
      attr("bb_standard", { enum: "BB30" }),
      attr("seatpost_diameter_mm", { num: 27.2, unit: "mm" }),
      attr("max_seatpost_insertion_mm", { num: 200, unit: "mm" }),
      attr("brake_mount_rear", { enum: "flat_mount" }),
      attr("max_rotor_rear_mm", { num: 160, unit: "mm" }),
      attr("max_tire_width_mm", { num: 32, unit: "mm" }),
      attr("motor_interface", { enum: "n/a", text: "n/a" }),
      attr("wheel_size_rear", { enum: "700c" }),
    ],
    adjusters: [],
    torqueSpecs: [],
    source: "oem",
    sourceUrl: "https://www.specialized.com/",
    verifiedAt: VERIFIED,
    verifiedBy: "FlowLine Editorial",
    safetyCritical: true,
  },
  {
    id: "cm-focus-jam2-frame",
    slot: "frame",
    manufacturer: "Focus",
    model: "JAM²",
    variant: "Bosch",
    modelYear: 2024,
    attributes: [
      attr("rear_spacing", { enum: "148x12_boost" }),
      attr("axle_rear", { enum: "12x148_boost" }),
      attr("headset_top", { enum: "ZS44" }),
      attr("headset_bottom", { enum: "ZS56" }),
      attr("bb_standard", { enum: "BSA73" }),
      attr("seatpost_diameter_mm", { num: 31.6, unit: "mm" }),
      attr("max_seatpost_insertion_mm", { num: 240, unit: "mm" }),
      attr("brake_mount_rear", { enum: "post_mount" }),
      attr("max_rotor_rear_mm", { num: 220, unit: "mm" }),
      attr("max_tire_width_mm", { num: 66, unit: "mm" }),
      attr("motor_interface", { enum: "bosch_smart_system" }),
      attr("wheel_size_rear", { enum: "29" }),
    ],
    adjusters: [],
    torqueSpecs: [],
    source: "oem",
    sourceUrl: "https://www.focus-bikes.com/",
    verifiedAt: VERIFIED,
    verifiedBy: "FlowLine Editorial",
    safetyCritical: true,
  },
  frameEtrekking({
    id: "cm-stevens-e-courier-frame",
    manufacturer: "Stevens",
    model: "E-Courier",
    url: "https://www.stevensbikes.de/",
  }),
  frameEtrekking({
    id: "cm-winora-yucatan-frame",
    manufacturer: "Winora",
    model: "Yucatan",
    url: "https://www.winora.com/",
  }),
  frameEtrekking({
    id: "cm-gazelle-ultimate-frame",
    manufacturer: "Gazelle",
    model: "Ultimate C8+",
    url: "https://www.gazellebikes.com/",
  }),
  frameEtrekking({
    id: "cm-bergamont-ehorizon-frame",
    manufacturer: "Bergamont",
    model: "E-Horizon",
    url: "https://www.bergamont.com/",
  }),
  frameEtrekking({
    id: "cm-ktm-macina-tour-frame",
    manufacturer: "KTM",
    model: "Macina Tour",
    url: "https://www.ktm-bikes.at/",
    seatpostMm: 30.9,
  }),
  {
    id: "cm-simplon-rapcon-frame",
    slot: "frame",
    manufacturer: "Simplon",
    model: "Rapcon",
    variant: "Carbon 170",
    modelYear: 2024,
    attributes: [
      attr("rear_spacing", { enum: "148x12_boost" }),
      attr("axle_rear", { enum: "12x148_boost" }),
      attr("shock_eye_to_eye_mm", { num: 230, unit: "mm" }),
      attr("shock_stroke_mm", { num: 65, unit: "mm" }),
      attr("shock_mount_type", { enum: "standard" }),
      attr("headset_top", { enum: "ZS56" }),
      attr("headset_bottom", { enum: "ZS56" }),
      attr("bb_standard", { enum: "PF92" }),
      attr("seatpost_diameter_mm", { num: 31.6, unit: "mm" }),
      attr("max_seatpost_insertion_mm", { num: 250, unit: "mm" }),
      attr("brake_mount_rear", { enum: "post_mount" }),
      attr("max_rotor_rear_mm", { num: 220, unit: "mm" }),
      attr("max_tire_width_mm", { num: 62, unit: "mm" }),
      attr("motor_interface", { enum: "n/a", text: "n/a" }),
      attr("wheel_size_rear", { enum: "29" }),
    ],
    adjusters: [],
    torqueSpecs: [],
    source: "oem",
    sourceUrl: "https://www.simplon.com/",
    verifiedAt: VERIFIED,
    verifiedBy: "FlowLine Editorial",
    safetyCritical: true,
  },
  {
    id: "cm-scott-genius-frame",
    slot: "frame",
    manufacturer: "Scott",
    model: "Genius",
    variant: "HMF Carbon",
    modelYear: 2024,
    attributes: [
      attr("rear_spacing", { enum: "148x12_boost" }),
      attr("axle_rear", { enum: "12x148_boost" }),
      attr("shock_eye_to_eye_mm", { num: 185, unit: "mm" }),
      attr("shock_stroke_mm", { num: 55, unit: "mm" }),
      attr("shock_mount_type", { enum: "trunnion" }),
      attr("headset_top", { enum: "ZS44" }),
      attr("headset_bottom", { enum: "ZS56" }),
      attr("bb_standard", { enum: "PF92" }),
      attr("seatpost_diameter_mm", { num: 31.6, unit: "mm" }),
      attr("max_seatpost_insertion_mm", { num: 250, unit: "mm" }),
      attr("brake_mount_rear", { enum: "post_mount" }),
      attr("max_rotor_rear_mm", { num: 203, unit: "mm" }),
      attr("max_tire_width_mm", { num: 66, unit: "mm" }),
      attr("motor_interface", { enum: "n/a", text: "n/a" }),
      attr("wheel_size_rear", { enum: "29" }),
    ],
    adjusters: [],
    torqueSpecs: [],
    source: "oem",
    sourceUrl: "https://www.scott-sports.com/",
    verifiedAt: VERIFIED,
    verifiedBy: "FlowLine Editorial",
    safetyCritical: true,
  },
  {
    id: "cm-yt-decoy-frame",
    slot: "frame",
    manufacturer: "YT",
    model: "Decoy MX",
    variant: "EP801",
    modelYear: 2024,
    attributes: [
      attr("rear_spacing", { enum: "148x12_boost" }),
      attr("axle_rear", { enum: "12x148_boost" }),
      attr("headset_top", { enum: "ZS44" }),
      attr("headset_bottom", { enum: "ZS56" }),
      attr("bb_standard", { enum: "BSA73" }),
      attr("seatpost_diameter_mm", { num: 31.6, unit: "mm" }),
      attr("max_seatpost_insertion_mm", { num: 240, unit: "mm" }),
      attr("brake_mount_rear", { enum: "post_mount" }),
      attr("max_rotor_rear_mm", { num: 220, unit: "mm" }),
      attr("max_tire_width_mm", { num: 66, unit: "mm" }),
      attr("motor_interface", { enum: "shimano_ep801" }),
      attr("wheel_size_rear", { enum: "27.5" }),
    ],
    adjusters: [],
    torqueSpecs: [],
    source: "oem",
    sourceUrl: "https://www.yt-industries.com/",
    verifiedAt: VERIFIED,
    verifiedBy: "FlowLine Editorial",
    safetyCritical: true,
  },

  // —— Gabeln / Dämpfer ——
  part("cm-canyon-gravel-fork", "fork", "Canyon", "FK0117 CF Disc", {
    variant: "Carbon 700c",
    year: 2024,
    url: "https://www.canyon.com/",
    safety: true,
    attrs: [
      attr("steerer_type", { enum: "tapered_1.5" }),
      attr("axle_front", { enum: "12x100" }),
      attr("brake_mount", { enum: "flat_mount" }),
      attr("max_rotor_mm", { num: 160, unit: "mm" }),
      attr("wheel_size", { enum: "700c" }),
    ],
  }),
  part("cm-canyon-road-fork", "fork", "Canyon", "Ultimate CF Fork", {
    variant: "Carbon 700c",
    year: 2024,
    url: "https://www.canyon.com/",
    safety: true,
    attrs: [
      attr("steerer_type", { enum: "tapered_1.5" }),
      attr("axle_front", { enum: "12x100" }),
      attr("brake_mount", { enum: "flat_mount" }),
      attr("max_rotor_mm", { num: 160, unit: "mm" }),
      attr("wheel_size", { enum: "700c" }),
    ],
  }),
  part("cm-suntour-nrx-d-75", "fork", "SR Suntour", "NRX-D Air", {
    variant: "75mm",
    year: 2024,
    url: "https://www.srsuntour.com/",
    safety: true,
    attrs: [
      attr("travel_mm", { num: 75, unit: "mm" }),
      attr("steerer_type", { enum: "straight_1.125" }),
      attr("axle_front", { enum: "9x100_qr" }),
      attr("brake_mount", { enum: "post_mount" }),
      attr("wheel_size", { enum: "700c" }),
    ],
  }),
  part("cm-suntour-ncx32-63", "fork", "SR Suntour", "NCX32-D Coil", {
    variant: "63mm",
    year: 2024,
    url: "https://www.srsuntour.com/",
    safety: true,
    attrs: [
      attr("travel_mm", { num: 63, unit: "mm" }),
      attr("steerer_type", { enum: "tapered_1.5" }),
      attr("axle_front", { enum: "9x100_qr" }),
      attr("brake_mount", { enum: "post_mount" }),
      attr("wheel_size", { enum: "29" }),
    ],
  }),
  part("cm-trek-fx-carbon-fork", "fork", "Trek", "FX Carbon", {
    variant: "ThruSkew QR",
    year: 2024,
    url: "https://www.trekbikes.com/",
    safety: true,
    attrs: [
      attr("steerer_type", { enum: "straight_1.125" }),
      attr("axle_front", { enum: "5x100_qr" }),
      attr("brake_mount", { enum: "flat_mount" }),
      attr("max_rotor_mm", { num: 160, unit: "mm" }),
      attr("wheel_size", { enum: "700c" }),
    ],
  }),
  part("cm-stevens-slite-fork", "fork", "Stevens", "S-Lite Aluminium", {
    variant: "Tapered",
    year: 2024,
    url: "https://www.stevensbikes.de/",
    safety: true,
    attrs: [
      attr("steerer_type", { enum: "tapered_1.5" }),
      attr("axle_front", { enum: "9x100_qr" }),
      attr("brake_mount", { enum: "post_mount" }),
      attr("wheel_size", { enum: "700c" }),
    ],
  }),
  part("cm-fox-36-pe-160", "fork", "Fox", "36 Performance Elite FIT4", {
    variant: "160mm 29",
    year: 2024,
    weightG: 2150,
    url: "https://www.ridefox.com/",
    safety: true,
    attrs: [
      attr("travel_mm", { num: 160, unit: "mm" }),
      attr("steerer_type", { enum: "tapered_1.5" }),
      attr("steerer_clamp_mm", { num: 28.6, unit: "mm" }),
      attr("axle_front", { enum: "15x110_boost" }),
      attr("brake_mount", { enum: "post_mount" }),
      attr("max_rotor_mm", { num: 230, unit: "mm" }),
      attr("wheel_size", { enum: "29" }),
      attr("offset_mm", { num: 44, unit: "mm" }),
    ],
  }),
  part("cm-fox-nude-5t-18555", "rear_shock", "Fox", "Nude 5T EVOL", {
    variant: "185×55 Trunnion",
    year: 2024,
    url: "https://www.ridefox.com/",
    safety: true,
    attrs: [
      attr("eye_to_eye_mm", { num: 185, unit: "mm" }),
      attr("stroke_mm", { num: 55, unit: "mm" }),
      attr("mount_type", { enum: "trunnion" }),
    ],
  }),

  // —— Gravel / Road Cockpit & Antrieb ——
  part("cm-cane-creek-is42-is52", "headset", "Cane Creek", "40 IS42/IS52", {
    url: "https://www.canecreek.com/",
    safety: true,
    attrs: [
      attr("headset_top", { enum: "IS42" }),
      attr("headset_bottom", { enum: "IS52" }),
    ],
  }),
  part("cm-easton-ea90-stem", "stem", "Easton", "EA90", {
    variant: "90mm 31.8",
    url: "https://eastoncycling.com/",
    safety: true,
    attrs: [attr("clamp_mm", { num: 31.8, unit: "mm" })],
  }),
  part("cm-easton-ec70-ax-bar", "handlebar", "Easton", "EC70 AX", {
    variant: "Drop 42cm",
    url: "https://eastoncycling.com/",
    safety: true,
    attrs: [
      attr("clamp_mm", { num: 31.8, unit: "mm" }),
      attr("drop_bar", { enum: "yes" }),
    ],
  }),
  part("cm-canyon-gravel-seatpost", "seatpost", "Canyon", "Iridium Gravel", {
    variant: "27.2",
    url: "https://www.canyon.com/",
    safety: true,
    attrs: [attr("diameter_mm", { num: 27.2, unit: "mm" })],
  }),
  part("cm-fizik-tempo-bar-tape", "bar_tape", "Fizik", "Tempo Microtex", {
    variant: "Bondcush",
    url: "https://www.fizik.com/",
    attrs: [attr("width_mm", { num: 3, unit: "mm" })],
  }),
  part("cm-dt-370-12x100-front", "front_hub", "DT Swiss", "370", {
    variant: "12x100 Center Lock",
    url: "https://www.dtswiss.com/",
    safety: true,
    attrs: [
      attr("axle_front", { enum: "12x100" }),
      attr("rotor_mount", { enum: "center_lock" }),
    ],
  }),
  part("cm-dt-370-12x142-rear-hg", "rear_hub", "DT Swiss", "370", {
    variant: "12x142 HG",
    url: "https://www.dtswiss.com/",
    safety: true,
    attrs: [
      attr("axle_rear", { enum: "12x142" }),
      attr("freehub_body", { enum: "HG" }),
      attr("rotor_mount", { enum: "center_lock" }),
    ],
  }),
  part("cm-shimano-grx-rx820-crank", "crankset", "Shimano", "GRX FC-RX820-1", {
    variant: "1x 172.5mm",
    url: SHIMANO,
    attrs: [
      attr("speed", { num: 12 }),
      attr("bcd", { enum: "direct_mount" }),
    ],
  }),
  part("cm-shimano-grx-chainring-42", "chainring", "Shimano", "GRX 42T", {
    url: SHIMANO,
    attrs: [attr("teeth", { num: 42 })],
  }),
  part("cm-shimano-grx-rx820-shifter", "shifter", "Shimano", "GRX ST-RX820", {
    variant: "1x12 hydraulic",
    url: SHIMANO,
    attrs: [attr("speed", { num: 12 })],
  }),
  part("cm-shimano-grx-rx820-front", "brake_front", "Shimano", "GRX BR-RX820", {
    variant: "Flat Mount",
    url: SHIMANO,
    safety: true,
    attrs: [
      attr("brake_mount", { enum: "flat_mount" }),
      attr("pistons", { num: 2 }),
    ],
  }),
  part("cm-shimano-grx-rx820-rear", "brake_rear", "Shimano", "GRX BR-RX820", {
    variant: "Flat Mount",
    url: SHIMANO,
    safety: true,
    attrs: [
      attr("brake_mount", { enum: "flat_mount" }),
      attr("pistons", { num: 2 }),
    ],
  }),
  part("cm-shimano-grx-fd", "front_derailleur", "Shimano", "GRX FD-RX820", {
    url: SHIMANO,
    attrs: [attr("speed", { num: 12 })],
  }),
  part("cm-shimano-bb-rs500-bsa68", "bottom_bracket", "Shimano", "BB-RS500", {
    variant: "BSA68",
    url: SHIMANO,
    attrs: [attr("bb_standard", { enum: "BSA68" })],
  }),
  part("cm-shimano-rt-mt800-160-front", "rotor_front", "Shimano", "Deore XT MT800", {
    variant: "160mm Center Lock",
    url: SHIMANO,
    safety: true,
    attrs: [
      attr("rotor_diameter_mm", { num: 160, unit: "mm" }),
      attr("rotor_mount", { enum: "center_lock" }),
    ],
  }),
  part("cm-shimano-rt-mt800-160-rear", "rotor_rear", "Shimano", "Deore XT MT800", {
    variant: "160mm Center Lock",
    url: SHIMANO,
    safety: true,
    attrs: [
      attr("rotor_diameter_mm", { num: 160, unit: "mm" }),
      attr("rotor_mount", { enum: "center_lock" }),
    ],
  }),
  part("cm-shimano-l03a-pads", "brake_pads_front", "Shimano", "L03A Resin", {
    url: SHIMANO,
    safety: true,
    attrs: [attr("compound", { enum: "resin" })],
  }),
  part("cm-shimano-l03a-pads-rear", "brake_pads_rear", "Shimano", "L03A Resin", {
    url: SHIMANO,
    safety: true,
    attrs: [attr("compound", { enum: "resin" })],
  }),
  part("cm-shimano-n03a-pads", "brake_pads_front", "Shimano", "N03A Metal", {
    url: SHIMANO,
    safety: true,
    attrs: [attr("compound", { enum: "metallic" })],
  }),
  part("cm-shimano-n03a-pads-rear", "brake_pads_rear", "Shimano", "N03A Metal", {
    url: SHIMANO,
    safety: true,
    attrs: [attr("compound", { enum: "metallic" })],
  }),
  part("cm-shimano-105-r7100-crank", "crankset", "Shimano", "105 FC-R7100", {
    variant: "50/34 172.5mm",
    url: SHIMANO,
    attrs: [attr("speed", { num: 12 })],
  }),
  part("cm-shimano-105-r7100-chainring", "chainring", "Shimano", "105 50/34", {
    url: SHIMANO,
    attrs: [attr("teeth", { num: 50 })],
  }),
  part("cm-shimano-105-r7100-fd", "front_derailleur", "Shimano", "105 FD-R7100", {
    url: SHIMANO,
    attrs: [attr("speed", { num: 12 })],
  }),
  part("cm-shimano-105-r7100-shifter", "shifter", "Shimano", "105 ST-R7170", {
    variant: "2x12 hydraulic",
    url: SHIMANO,
    attrs: [attr("speed", { num: 12 })],
  }),
  part("cm-shimano-105-r7170-front", "brake_front", "Shimano", "105 BR-R7170", {
    variant: "Flat Mount",
    url: SHIMANO,
    safety: true,
    attrs: [attr("brake_mount", { enum: "flat_mount" })],
  }),
  part("cm-shimano-105-r7170-rear", "brake_rear", "Shimano", "105 BR-R7170", {
    variant: "Flat Mount",
    url: SHIMANO,
    safety: true,
    attrs: [attr("brake_mount", { enum: "flat_mount" })],
  }),
  part("cm-shimano-cn-m7100", "chain", "Shimano", "CN-M7100", {
    variant: "12s HG+",
    url: SHIMANO,
    attrs: [attr("speed", { num: 12 })],
  }),
  part("cm-shimano-pd-rs500", "pedals", "Shimano", "PD-RS500", {
    variant: "SPD-SL",
    url: SHIMANO,
    attrs: [attr("cleat", { enum: "spd_sl" })],
  }),

  // —— Urban 1x / IGH ——
  part("cm-shimano-deore-m5120-rd", "rear_derailleur", "Shimano", "Deore RD-M5120", {
    variant: "SGS 10/11s",
    url: SHIMANO,
    attrs: [attr("speed", { num: 10 }), attr("max_cog", { num: 46 })],
  }),
  part("cm-shimano-deore-m4100-cassette", "cassette", "Shimano", "Deore CS-M4100", {
    variant: "11-46 10s",
    url: SHIMANO,
    attrs: [
      attr("cassette_speed", { num: 10 }),
      attr("freehub_body", { enum: "HG" }),
    ],
  }),
  part("cm-shimano-deore-m4100-shifter", "shifter", "Shimano", "Deore SL-M4100", {
    variant: "10s",
    url: SHIMANO,
    attrs: [attr("speed", { num: 10 })],
  }),
  part("cm-kmc-x10-chain", "chain", "KMC", "X10", {
    url: "https://www.kmcchain.com/",
    attrs: [attr("speed", { num: 10 })],
  }),
  part("cm-prowheel-40-crank", "crankset", "Prowheel", "Alloy 1x", {
    variant: "40T 170mm",
    url: "https://www.trekbikes.com/",
    attrs: [attr("teeth", { num: 40 })],
  }),
  part("cm-prowheel-40-ring", "chainring", "Prowheel", "Narrow-Wide 40T", {
    url: "https://www.trekbikes.com/",
    attrs: [attr("teeth", { num: 40 })],
  }),
  part("cm-shimano-xt-m8100-36-crank", "crankset", "Shimano", "Deore XT FC-M8100", {
    variant: "36T",
    url: SHIMANO,
    attrs: [attr("teeth", { num: 36 })],
  }),
  part("cm-shimano-mt200-front", "brake_front", "Shimano", "BR-MT200", {
    url: SHIMANO,
    safety: true,
    attrs: [
      attr("brake_mount", { enum: "post_mount" }),
      attr("pistons", { num: 2 }),
    ],
  }),
  part("cm-shimano-mt200-rear", "brake_rear", "Shimano", "BR-MT200", {
    url: SHIMANO,
    safety: true,
    attrs: [
      attr("brake_mount", { enum: "post_mount" }),
      attr("pistons", { num: 2 }),
    ],
  }),
  part("cm-shimano-mt410-front", "brake_front", "Shimano", "BR-MT410", {
    url: SHIMANO,
    safety: true,
    attrs: [
      attr("brake_mount", { enum: "post_mount" }),
      attr("pistons", { num: 2 }),
    ],
  }),
  part("cm-shimano-mt410-rear", "brake_rear", "Shimano", "BR-MT410", {
    url: SHIMANO,
    safety: true,
    attrs: [
      attr("brake_mount", { enum: "post_mount" }),
      attr("pistons", { num: 2 }),
    ],
  }),
  part("cm-shimano-rt54-160-front", "rotor_front", "Shimano", "SM-RT54", {
    variant: "160mm",
    url: SHIMANO,
    safety: true,
    attrs: [attr("rotor_diameter_mm", { num: 160, unit: "mm" })],
  }),
  part("cm-shimano-rt54-160-rear", "rotor_rear", "Shimano", "SM-RT54", {
    variant: "160mm",
    url: SHIMANO,
    safety: true,
    attrs: [attr("rotor_diameter_mm", { num: 160, unit: "mm" })],
  }),
  part("cm-shimano-rt30-180-front", "rotor_front", "Shimano", "SM-RT30", {
    variant: "180mm Center Lock",
    url: SHIMANO,
    safety: true,
    attrs: [
      attr("rotor_diameter_mm", { num: 180, unit: "mm" }),
      attr("rotor_mount", { enum: "center_lock" }),
    ],
  }),
  part("cm-shimano-rt30-160-rear", "rotor_rear", "Shimano", "SM-RT30", {
    variant: "160mm Center Lock",
    url: SHIMANO,
    safety: true,
    attrs: [
      attr("rotor_diameter_mm", { num: 160, unit: "mm" }),
      attr("rotor_mount", { enum: "center_lock" }),
    ],
  }),
  part("cm-b01s-pads", "brake_pads_front", "Shimano", "B01S Resin", {
    url: SHIMANO,
    safety: true,
    attrs: [attr("compound", { enum: "resin" })],
  }),
  part("cm-b01s-pads-rear", "brake_pads_rear", "Shimano", "B01S Resin", {
    url: SHIMANO,
    safety: true,
    attrs: [attr("compound", { enum: "resin" })],
  }),
  part("cm-ergon-gp1-grips", "grips", "Ergon", "GP1", {
    url: "https://www.ergonbike.com/",
    attrs: [attr("shape", { enum: "wing" })],
  }),
  part("cm-vp-city-pedals", "pedals", "VP", "City/Trekking", {
    url: "https://www.vpcomponents.com/",
    attrs: [attr("type", { enum: "flat" })],
  }),
  part("cm-gates-cdx-belt", "chain", "Gates", "CDX Center Track Belt", {
    url: "https://www.gatescarbondrive.com/",
    attrs: [attr("drive", { enum: "belt" })],
  }),
  part("cm-gates-cdx-ring", "chainring", "Gates", "CDX Front Sprocket", {
    variant: "50T",
    url: "https://www.gatescarbondrive.com/",
    attrs: [attr("teeth", { num: 50 })],
  }),
  part("cm-gates-cdx-rear", "cassette", "Gates", "CDX Rear Sprocket", {
    variant: "24T",
    url: "https://www.gatescarbondrive.com/",
    attrs: [attr("teeth", { num: 24 })],
  }),
  part("cm-gates-cdn-crank", "crankset", "Gates", "CDN S150", {
    variant: "170mm",
    url: "https://www.gatescarbondrive.com/",
    attrs: [attr("drive", { enum: "belt" })],
  }),
  part("cm-shimano-alfine-s7001", "rear_hub", "Shimano", "Alfine SG-S7001-11", {
    variant: "11s IGH 135mm",
    url: SHIMANO,
    safety: true,
    attrs: [
      attr("igh_speeds", { num: 11 }),
      attr("axle_rear", { enum: "135x10" }),
      attr("range_pct", { num: 409, unit: "%" }),
    ],
  }),
  part("cm-shimano-alfine-sl-s700", "shifter", "Shimano", "Alfine SL-S700", {
    variant: "11s",
    url: SHIMANO,
    attrs: [attr("speed", { num: 11 })],
  }),
  part("cm-shimano-dh-3d37", "front_hub", "Shimano", "DH-3D37 Dynamo", {
    url: SHIMANO,
    safety: true,
    attrs: [
      attr("dynamo", { enum: "yes" }),
      attr("rotor_mount", { enum: "center_lock" }),
    ],
  }),
  part("cm-formula-dc20", "front_hub", "Formula", "DC-20", {
    variant: "5x100 QR 6-bolt",
    url: "https://www.formula-hub.com/",
    safety: true,
    attrs: [
      attr("axle_front", { enum: "5x100_qr" }),
      attr("rotor_mount", { enum: "6_bolt" }),
    ],
  }),
  part("cm-formula-dc22", "rear_hub", "Formula", "DC-22", {
    variant: "135x5 QR HG",
    url: "https://www.formula-hub.com/",
    safety: true,
    attrs: [
      attr("axle_rear", { enum: "135x5_qr" }),
      attr("freehub_body", { enum: "HG" }),
    ],
  }),
  part("cm-alexrims-gx26", "front_rim", "Alexrims", "GX26P", {
    url: "https://www.alexrims.com/",
    safety: true,
    attrs: [attr("wheel_size", { enum: "700c" })],
  }),
  part("cm-alexrims-gx26-rear", "rear_rim", "Alexrims", "GX26P", {
    url: "https://www.alexrims.com/",
    safety: true,
    attrs: [attr("wheel_size", { enum: "700c" })],
  }),
  part("cm-bontrager-tlr-rim-front", "front_rim", "Bontrager", "Tubeless Ready Disc", {
    url: "https://www.trekbikes.com/",
    safety: true,
    attrs: [attr("wheel_size", { enum: "700c" })],
  }),
  part("cm-bontrager-tlr-rim-rear", "rear_rim", "Bontrager", "Tubeless Ready Disc", {
    url: "https://www.trekbikes.com/",
    safety: true,
    attrs: [attr("wheel_size", { enum: "700c" })],
  }),
  part("cm-continental-contact-urban", "tire_front", "Continental", "Contact Urban", {
    variant: "42-622",
    url: "https://www.continental-tires.com/",
    safety: true,
    attrs: [
      attr("tire_width_mm", { num: 42, unit: "mm" }),
      attr("etrto", { text: "42-622" }),
    ],
  }),
  part("cm-schwalbe-g-one-r-40", "tire_front", "Schwalbe", "G-One R", {
    variant: "40-622",
    url: "https://www.schwalbe.com/",
    safety: true,
    attrs: [
      attr("tire_width_mm", { num: 40, unit: "mm" }),
      attr("etrto", { text: "40-622" }),
    ],
  }),

  // —— E-Trekking Antrieb ——
  part("cm-shimano-alivio-m3100-rd", "rear_derailleur", "Shimano", "Alivio RD-M3100", {
    variant: "9s SGS",
    url: SHIMANO,
    attrs: [attr("speed", { num: 9 })],
  }),
  part("cm-shimano-alivio-m3100-shifter", "shifter", "Shimano", "Alivio SL-M3100", {
    variant: "9s",
    url: SHIMANO,
    attrs: [attr("speed", { num: 9 })],
  }),
  part("cm-shimano-hg201-9", "cassette", "Shimano", "CS-HG201", {
    variant: "11-36 9s",
    url: SHIMANO,
    attrs: [attr("cassette_speed", { num: 9 })],
  }),
  part("cm-shimano-e6070-chain", "chain", "Shimano", "CN-E6070", {
    variant: "9s e-bike",
    url: SHIMANO,
    attrs: [attr("speed", { num: 9 })],
  }),
  part("cm-ktm-eline-crank", "crankset", "KTM", "E-LINE BNI", {
    variant: "170mm",
    url: "https://www.ktm-bikes.at/",
    attrs: [attr("motor_interface", { enum: "bosch_smart_system" })],
  }),
  part("cm-fsa-40-ring", "chainring", "FSA", "Direct Mount Steel 40T", {
    url: "https://www.fullspeedahead.com/",
    attrs: [attr("teeth", { num: 40 })],
  }),
  part("cm-bosch-powertube-500", "battery", "Bosch", "PowerTube", {
    variant: "500 Wh",
    url: BOSCH,
    safety: true,
    attrs: [
      attr("capacity_wh", { num: 500, unit: "Wh" }),
      attr("battery_system", { enum: "bosch_smart_system" }),
    ],
  }),
  part("cm-bosch-intuvia-100", "display", "Bosch", "Intuvia 100", {
    variant: "Smart System",
    url: BOSCH,
    attrs: [attr("display_system", { enum: "bosch_smart_system" })],
  }),
  part("cm-bosch-performance-line", "motor", "Bosch", "Performance Line", {
    variant: "Smart System 75 Nm",
    url: BOSCH,
    safety: true,
    attrs: [
      attr("motor_system", { enum: "bosch_smart_system" }),
      attr("max_torque_nm", { num: 75, unit: "Nm" }),
    ],
  }),
  part("cm-shimano-ep801", "motor", "Shimano", "STEPS EP801", {
    variant: "85 Nm",
    url: SHIMANO,
    safety: true,
    attrs: [
      attr("motor_system", { enum: "shimano_ep801" }),
      attr("max_torque_nm", { num: 85, unit: "Nm" }),
    ],
  }),
  part("cm-yt-battery-720", "battery", "YT", "Decoy Battery", {
    variant: "720 Wh",
    url: "https://www.yt-industries.com/",
    safety: true,
    attrs: [
      attr("capacity_wh", { num: 720, unit: "Wh" }),
      attr("battery_system", { enum: "shimano_ep801" }),
    ],
  }),
  part("cm-shimano-sc-em800", "display", "Shimano", "SC-EM800", {
    url: SHIMANO,
    attrs: [attr("display_system", { enum: "shimano_ep801" })],
  }),
  part("cm-sram-dub-pf92", "bottom_bracket", "SRAM", "DUB PF92", {
    url: "https://www.sram.com/",
    attrs: [attr("bb_standard", { enum: "PF92" })],
  }),
  part("cm-ktm-line-seatpost", "seatpost", "KTM", "Line Elegance", {
    variant: "30.9 susp.",
    url: "https://www.ktm-bikes.at/",
    safety: true,
    attrs: [attr("diameter_mm", { num: 30.9, unit: "mm" })],
  }),

  // —— Round 7: Ekano / Rail / Numinis / Corratec (nur OEM-Maße) ——
  {
    id: "cm-propain-ekano-frame",
    slot: "frame",
    manufacturer: "Propain",
    model: "Ekano 2 AL",
    variant: "EP801 Mullet",
    modelYear: 2025,
    attributes: [
      attr("rear_spacing", { enum: "148x12_boost" }),
      attr("axle_rear", { enum: "12x148_boost" }),
      attr("shock_eye_to_eye_mm", { num: 205, unit: "mm" }),
      attr("shock_stroke_mm", { num: 60, unit: "mm" }),
      attr("shock_mount_type", { enum: "trunnion" }),
      attr("headset_top", { enum: "ZS56" }),
      attr("headset_bottom", { enum: "ZS56" }),
      attr("bb_standard", { enum: "BSA73" }),
      attr("seatpost_diameter_mm", { num: 31.6, unit: "mm" }),
      attr("brake_mount_rear", { enum: "post_mount" }),
      attr("max_rotor_rear_mm", { num: 203, unit: "mm" }),
      attr("max_tire_width_mm", { num: 66, unit: "mm" }),
      attr("motor_interface", { enum: "shimano_ep801" }),
      attr("wheel_size_rear", { enum: "27.5" }),
    ],
    adjusters: [],
    torqueSpecs: [],
    source: "oem",
    sourceUrl: "https://www.propain-bikes.com/en/the-all-new-ekano-2-al/",
    verifiedAt: VERIFIED,
    verifiedBy: "FlowLine Editorial",
    safetyCritical: true,
  },
  {
    id: "cm-trek-rail-frame",
    slot: "frame",
    manufacturer: "Trek",
    model: "Rail Gen 4",
    variant: "OCLV Carbon",
    modelYear: 2024,
    attributes: [
      attr("rear_spacing", { enum: "148x12_boost" }),
      attr("axle_rear", { enum: "12x148_boost" }),
      attr("headset_top", { enum: "ZS44" }),
      attr("headset_bottom", { enum: "ZS56" }),
      attr("bb_standard", { enum: "BSA73" }),
      attr("seatpost_diameter_mm", { num: 34.9, unit: "mm" }),
      attr("max_seatpost_insertion_mm", { num: 250, unit: "mm" }),
      attr("brake_mount_rear", { enum: "post_mount" }),
      attr("max_rotor_rear_mm", { num: 203, unit: "mm" }),
      attr("max_tire_width_mm", { num: 66, unit: "mm" }),
      attr("motor_interface", { enum: "bosch_smart_system" }),
      attr("wheel_size_rear", { enum: "29" }),
    ],
    adjusters: [],
    torqueSpecs: [],
    source: "oem",
    sourceUrl:
      "https://www.trekbikes.com/us/en_US/bikes/mountain-bikes/electric-mountain-bikes/rail/rail-9-7-gen-4/p/37026/",
    verifiedAt: VERIFIED,
    verifiedBy: "FlowLine Editorial",
    safetyCritical: true,
  },
  {
    id: "cm-centurion-numinis-frame",
    slot: "frame",
    manufacturer: "Centurion",
    model: "Numinis R",
    variant: "TBN002B Aluminium",
    modelYear: 2026,
    attributes: [
      attr("rear_spacing", { enum: "148x12_boost" }),
      attr("axle_rear", { enum: "12x148_boost" }),
      attr("headset_top", { enum: "ZS44" }),
      attr("headset_bottom", { enum: "ZS56" }),
      attr("bb_standard", { enum: "BSA73" }),
      attr("seatpost_diameter_mm", { num: 34.9, unit: "mm" }),
      attr("max_seatpost_insertion_mm", { num: 250, unit: "mm" }),
      attr("brake_mount_rear", { enum: "post_mount" }),
      attr("max_rotor_rear_mm", { num: 203, unit: "mm" }),
      attr("max_tire_width_mm", { num: 66, unit: "mm" }),
      attr("motor_interface", { enum: "bosch_smart_system" }),
      attr("wheel_size_rear", { enum: "29" }),
    ],
    adjusters: [],
    torqueSpecs: [],
    source: "oem",
    sourceUrl: "https://www.centurion.de/de-de/bike/1213/numinis-r2000",
    verifiedAt: VERIFIED,
    verifiedBy: "FlowLine Editorial",
    safetyCritical: true,
  },
  {
    id: "cm-corratec-ep-ilink-frame",
    slot: "frame",
    manufacturer: "Corratec",
    model: "E-Power iLink",
    variant: "Race Aluminium",
    modelYear: 2025,
    attributes: [
      attr("rear_spacing", { enum: "148x12_boost" }),
      attr("axle_rear", { enum: "12x148_boost" }),
      attr("headset_top", { enum: "ZS44" }),
      attr("headset_bottom", { enum: "ZS56" }),
      attr("bb_standard", { enum: "BSA73" }),
      attr("seatpost_diameter_mm", { num: 31.6, unit: "mm" }),
      attr("max_seatpost_insertion_mm", { num: 250, unit: "mm" }),
      attr("brake_mount_rear", { enum: "post_mount" }),
      attr("max_rotor_rear_mm", { num: 203, unit: "mm" }),
      attr("max_tire_width_mm", { num: 70, unit: "mm" }),
      attr("motor_interface", { enum: "bosch_smart_system" }),
      attr("wheel_size_rear", { enum: "27.5" }),
    ],
    adjusters: [],
    torqueSpecs: [],
    source: "oem",
    sourceUrl:
      "https://www.corratec.com/en/Bike-Archive/E-Bikes/E-Power-iLink-Race-Silver-Gray-Pearlized-Black-Red-Anthracite-42.html",
    verifiedAt: VERIFIED,
    verifiedBy: "FlowLine Editorial",
    safetyCritical: true,
  },
  part("cm-fox-38-factory-180", "fork", "Fox", "38 Factory Grip2", {
    variant: "180mm 29",
    year: 2024,
    url: "https://www.ridefox.com/",
    safety: true,
    attrs: [
      attr("travel_mm", { num: 180, unit: "mm" }),
      attr("steerer_type", { enum: "tapered_1.5" }),
      attr("steerer_clamp_mm", { num: 28.6, unit: "mm" }),
      attr("axle_front", { enum: "15x110_boost" }),
      attr("brake_mount", { enum: "post_mount" }),
      attr("max_rotor_mm", { num: 230, unit: "mm" }),
      attr("wheel_size", { enum: "29" }),
      attr("offset_mm", { num: 44, unit: "mm" }),
    ],
  }),
  part("cm-rockshox-yari-180", "fork", "RockShox", "Yari RC", {
    variant: "180mm 29 Motion Control",
    year: 2025,
    url: "https://www.sram.com/",
    safety: true,
    attrs: [
      attr("travel_mm", { num: 180, unit: "mm" }),
      attr("steerer_type", { enum: "tapered_1.5" }),
      attr("axle_front", { enum: "15x110_boost" }),
      attr("brake_mount", { enum: "post_mount" }),
      attr("wheel_size", { enum: "29" }),
    ],
  }),
  part("cm-rockshox-deluxe-230575", "rear_shock", "RockShox", "Deluxe Select+ RT", {
    variant: "230×57.5",
    year: 2024,
    url: "https://www.sram.com/",
    safety: true,
    attrs: [
      attr("eye_to_eye_mm", { num: 230, unit: "mm" }),
      attr("stroke_mm", { num: 57.5, unit: "mm" }),
    ],
  }),
  part(
    "cm-centurion-numinis-shock",
    "rear_shock",
    "Centurion",
    "Numinis R Dämpfer",
    {
      variant: "210×52.5",
      year: 2026,
      url: "https://www.centurion.de/de-de/bike/1213/numinis-r2000",
      safety: true,
      attrs: [
        attr("eye_to_eye_mm", { num: 210, unit: "mm" }),
        attr("stroke_mm", { num: 52.5, unit: "mm" }),
      ],
    }
  ),
  part("cm-propain-battery-626", "battery", "Propain", "Ekano Battery", {
    variant: "626 Wh",
    url: "https://www.propain-bikes.com/en/the-all-new-ekano-2-al/",
    safety: true,
    attrs: [
      attr("capacity_wh", { num: 626, unit: "Wh" }),
      attr("battery_system", { enum: "shimano_ep801" }),
    ],
  }),
  part("cm-bosch-powertube-625", "battery", "Bosch", "PowerTube", {
    variant: "625 Wh",
    url: "https://www.bosch-ebike.com/",
    safety: true,
    attrs: [
      attr("capacity_wh", { num: 625, unit: "Wh" }),
      attr("battery_system", { enum: "bosch_smart_system" }),
    ],
  }),
  part("cm-bosch-cx-race", "motor", "Bosch", "Performance Line CX Race", {
    variant: "Smart System 85 Nm",
    url: "https://www.bosch-ebike.com/",
    safety: true,
    attrs: [
      attr("motor_system", { enum: "bosch_smart_system" }),
      attr("max_torque_nm", { num: 85, unit: "Nm" }),
    ],
  }),
  part("cm-bosch-purion-200", "display", "Bosch", "Purion 200", {
    variant: "Smart System",
    url: "https://www.bosch-ebike.com/",
    attrs: [attr("display_system", { enum: "bosch_smart_system" })],
  }),

  // —— Round 8: Strive / Rapcon :e / Path Riot / GRX 2× ——
  {
    id: "cm-canyon-strive-cfr-frame",
    slot: "frame",
    manufacturer: "Canyon",
    model: "Strive CFR",
    variant: "Shapeshifter",
    modelYear: 2024,
    attributes: [
      attr("rear_spacing", { enum: "148x12_boost" }),
      attr("axle_rear", { enum: "12x148_boost" }),
      attr("shock_eye_to_eye_mm", { num: 230, unit: "mm" }),
      attr("shock_stroke_mm", { num: 65, unit: "mm" }),
      attr("headset_top", { enum: "ZS44" }),
      attr("headset_bottom", { enum: "ZS56" }),
      attr("bb_standard", { enum: "BSA73" }),
      attr("seatpost_diameter_mm", { num: 30.9, unit: "mm" }),
      attr("max_seatpost_insertion_mm", { num: 250, unit: "mm" }),
      attr("brake_mount_rear", { enum: "post_mount" }),
      attr("max_rotor_rear_mm", { num: 200, unit: "mm" }),
      attr("max_tire_width_mm", { num: 66, unit: "mm" }),
      attr("motor_interface", { enum: "n/a", text: "n/a" }),
      attr("wheel_size_rear", { enum: "29" }),
    ],
    adjusters: [],
    torqueSpecs: [],
    source: "oem",
    sourceUrl:
      "https://www.canyon.com/en-de/productpdf/geometry/?pid=3416",
    verifiedAt: VERIFIED,
    verifiedBy: "FlowLine Editorial",
    safetyCritical: true,
  },
  {
    id: "cm-simplon-rapcon-e-frame",
    slot: "frame",
    manufacturer: "Simplon",
    model: "Rapcon :e",
    variant: "Bosch CX Gen5",
    modelYear: 2026,
    attributes: [
      attr("rear_spacing", { enum: "148x12_boost" }),
      attr("axle_rear", { enum: "12x148_boost" }),
      attr("shock_eye_to_eye_mm", { num: 205, unit: "mm" }),
      attr("shock_stroke_mm", { num: 62.5, unit: "mm" }),
      attr("shock_mount_type", { enum: "trunnion" }),
      attr("headset_top", { enum: "ZS56" }),
      attr("headset_bottom", { enum: "ZS66" }),
      attr("bb_standard", { enum: "BSA73" }),
      attr("seatpost_diameter_mm", { num: 31.6, unit: "mm" }),
      attr("max_seatpost_insertion_mm", { num: 250, unit: "mm" }),
      attr("brake_mount_rear", { enum: "post_mount" }),
      attr("max_rotor_rear_mm", { num: 220, unit: "mm" }),
      attr("max_tire_width_mm", { num: 65, unit: "mm" }),
      attr("motor_interface", { enum: "bosch_smart_system" }),
      attr("wheel_size_rear", { enum: "29" }),
    ],
    adjusters: [],
    torqueSpecs: [],
    source: "oem",
    sourceUrl:
      "https://www.simplon.com/en/Bikes/E-Mountain-Bikes/Rapcon-e_b_1149826",
    verifiedAt: VERIFIED,
    verifiedBy: "FlowLine Editorial",
    safetyCritical: true,
  },
  {
    id: "cm-ghost-path-riot-frame",
    slot: "frame",
    manufacturer: "Ghost",
    model: "Path Riot",
    variant: "Advanced Carbon Fazua",
    modelYear: 2026,
    attributes: [
      attr("rear_spacing", { enum: "148x12_boost" }),
      attr("axle_rear", { enum: "12x148_boost" }),
      attr("shock_eye_to_eye_mm", { num: 185, unit: "mm" }),
      attr("shock_stroke_mm", { num: 55, unit: "mm" }),
      attr("shock_mount_type", { enum: "trunnion" }),
      attr("headset_top", { enum: "ZS44" }),
      attr("headset_bottom", { enum: "ZS56" }),
      attr("bb_standard", { enum: "fazua_ride_60" }),
      attr("seatpost_diameter_mm", { num: 34.9, unit: "mm" }),
      attr("brake_mount_rear", { enum: "post_mount" }),
      attr("max_rotor_rear_mm", { num: 203, unit: "mm" }),
      attr("max_tire_width_mm", { num: 66, unit: "mm" }),
      attr("motor_interface", { enum: "fazua_ride_60" }),
      attr("wheel_size_rear", { enum: "29" }),
    ],
    adjusters: [],
    torqueSpecs: [],
    source: "oem",
    sourceUrl: "https://ghost-bikes.com/en-int/products/path-riot-advanced-gfat1",
    verifiedAt: VERIFIED,
    verifiedBy: "FlowLine Editorial",
    safetyCritical: true,
  },
  part("cm-simplon-rapcon-e-shock", "rear_shock", "Simplon", "Rapcon :e Dämpfer", {
    variant: "205×62.5 Trunnion",
    year: 2026,
    url: "https://www.simplon.com/en/Bikes/E-Mountain-Bikes/Rapcon-e_b_1149826",
    safety: true,
    attrs: [
      attr("eye_to_eye_mm", { num: 205, unit: "mm" }),
      attr("stroke_mm", { num: 62.5, unit: "mm" }),
      attr("mount_type", { enum: "trunnion" }),
    ],
  }),
  part("cm-rockshox-superdeluxe-18555", "rear_shock", "RockShox", "Super Deluxe Select RT", {
    variant: "185×55",
    year: 2026,
    url: "https://www.sram.com/",
    safety: true,
    attrs: [
      attr("eye_to_eye_mm", { num: 185, unit: "mm" }),
      attr("stroke_mm", { num: 55, unit: "mm" }),
      attr("mount_type", { enum: "trunnion" }),
    ],
  }),
  part("cm-fazua-ride-60", "motor", "Fazua", "Ride 60", {
    variant: "60 Nm",
    url: "https://www.fazua.com/",
    safety: true,
    attrs: [
      attr("motor_system", { enum: "fazua_ride_60" }),
      attr("max_torque_nm", { num: 60, unit: "Nm" }),
    ],
  }),
  part("cm-fazua-energy-480", "battery", "Fazua", "Energy", {
    variant: "480 Wh",
    url: "https://www.fazua.com/",
    safety: true,
    attrs: [
      attr("capacity_wh", { num: 480, unit: "Wh" }),
      attr("battery_system", { enum: "fazua_ride_60" }),
    ],
  }),
  part("cm-shimano-grx-rx820-crank-2x", "crankset", "Shimano", "GRX FC-RX820-2", {
    variant: "2x 172.5mm",
    url: SHIMANO,
    attrs: [
      attr("speed", { num: 12 }),
      attr("chainrings", { num: 2 }),
    ],
  }),
  part("cm-shimano-grx-chainring-48", "chainring", "Shimano", "GRX 48/31", {
    url: SHIMANO,
    attrs: [attr("teeth", { num: 48 })],
  }),
  part("cm-praxis-alba-crank", "crankset", "Praxis", "Alba", {
    variant: "48/32",
    url: "https://www.praxiscycles.com/",
    attrs: [attr("chainrings", { num: 2 })],
  }),
  part("cm-praxis-alba-ring", "chainring", "Praxis", "Alba 48/32", {
    url: "https://www.praxiscycles.com/",
    attrs: [attr("teeth", { num: 48 })],
  }),

  // —— Propain OEM (Herstellerseiten 2025/26) ——
  {
    id: "cm-propain-tyee-cf-frame",
    slot: "frame",
    manufacturer: "Propain",
    model: "Tyee 6.1",
    variant: "CF",
    modelYear: 2025,
    attributes: [
      attr("rear_spacing", { enum: "148x12_boost" }),
      attr("axle_rear", { enum: "12x148_boost" }),
      attr("shock_eye_to_eye_mm", { num: 210, unit: "mm" }),
      attr("shock_stroke_mm", { num: 55, unit: "mm" }),
      attr("shock_mount_type", { enum: "standard" }),
      attr("headset_top", { enum: "ZS56" }),
      attr("headset_bottom", { enum: "ZS56" }),
      attr("bb_standard", { enum: "BSA73" }),
      attr("seatpost_diameter_mm", { num: 31.6, unit: "mm" }),
      attr("brake_mount_rear", { enum: "post_mount" }),
      attr("max_rotor_rear_mm", { num: 203, unit: "mm" }),
      attr("motor_interface", { enum: "n/a", text: "n/a" }),
      attr("wheel_size_rear", { enum: "29" }),
    ],
    adjusters: [],
    torqueSpecs: [],
    source: "oem",
    sourceUrl: "https://www.propain-bikes.com/en/product/bikes/enduro/tyee-cf/",
    verifiedAt: VERIFIED,
    verifiedBy: "FlowLine Editorial",
    safetyCritical: true,
  },
  {
    id: "cm-propain-tyee-trail-frame",
    slot: "frame",
    manufacturer: "Propain",
    model: "Tyee 6.1 Trail",
    variant: "AL",
    modelYear: 2025,
    attributes: [
      attr("rear_spacing", { enum: "148x12_boost" }),
      attr("axle_rear", { enum: "12x148_boost" }),
      attr("shock_eye_to_eye_mm", { num: 210, unit: "mm" }),
      attr("shock_stroke_mm", { num: 50, unit: "mm" }),
      attr("shock_mount_type", { enum: "standard" }),
      attr("headset_top", { enum: "ZS56" }),
      attr("headset_bottom", { enum: "ZS56" }),
      attr("bb_standard", { enum: "BSA73" }),
      attr("seatpost_diameter_mm", { num: 31.6, unit: "mm" }),
      attr("brake_mount_rear", { enum: "post_mount" }),
      attr("max_rotor_rear_mm", { num: 200, unit: "mm" }),
      attr("motor_interface", { enum: "n/a", text: "n/a" }),
      attr("wheel_size_rear", { enum: "29" }),
    ],
    adjusters: [],
    torqueSpecs: [],
    source: "oem",
    sourceUrl: "https://www.propain-bikes.com/en/product/bikes/enduro/tyee-al-trail/",
    verifiedAt: VERIFIED,
    verifiedBy: "FlowLine Editorial",
    safetyCritical: true,
  },
  {
    id: "cm-propain-spindrift-cf-frame",
    slot: "frame",
    manufacturer: "Propain",
    model: "Spindrift 5",
    variant: "CF",
    modelYear: 2025,
    attributes: [
      attr("rear_spacing", { enum: "148x12_boost" }),
      attr("axle_rear", { enum: "12x148_boost" }),
      attr("shock_eye_to_eye_mm", { num: 230, unit: "mm" }),
      attr("shock_stroke_mm", { num: 65, unit: "mm" }),
      attr("shock_mount_type", { enum: "standard" }),
      attr("headset_top", { enum: "ZS56" }),
      attr("headset_bottom", { enum: "ZS56" }),
      attr("bb_standard", { enum: "BSA73" }),
      attr("seatpost_diameter_mm", { num: 31.6, unit: "mm" }),
      attr("brake_mount_rear", { enum: "post_mount" }),
      attr("max_rotor_rear_mm", { num: 200, unit: "mm" }),
      attr("motor_interface", { enum: "n/a", text: "n/a" }),
      attr("wheel_size_rear", { enum: "29" }),
    ],
    adjusters: [],
    torqueSpecs: [],
    source: "oem",
    sourceUrl: "https://www.propain-bikes.com/en/product/bikes/freeride/spindrift-cf/",
    verifiedAt: VERIFIED,
    verifiedBy: "FlowLine Editorial",
    safetyCritical: true,
  },
  {
    id: "cm-propain-spindrift-al-dc-frame",
    slot: "frame",
    manufacturer: "Propain",
    model: "Spindrift 5 Dual Crown",
    variant: "AL",
    modelYear: 2025,
    attributes: [
      attr("rear_spacing", { enum: "148x12_boost" }),
      attr("axle_rear", { enum: "12x148_boost" }),
      attr("shock_eye_to_eye_mm", { num: 230, unit: "mm" }),
      attr("shock_stroke_mm", { num: 65, unit: "mm" }),
      attr("shock_mount_type", { enum: "standard" }),
      attr("headset_top", { enum: "ZS49" }),
      attr("headset_bottom", { enum: "ZS56" }),
      attr("bb_standard", { enum: "BSA73" }),
      attr("seatpost_diameter_mm", { num: 31.6, unit: "mm" }),
      attr("brake_mount_rear", { enum: "post_mount" }),
      attr("max_rotor_rear_mm", { num: 180, unit: "mm" }),
      attr("motor_interface", { enum: "n/a", text: "n/a" }),
      attr("wheel_size_rear", { enum: "27.5" }),
    ],
    adjusters: [],
    torqueSpecs: [],
    source: "oem",
    sourceUrl:
      "https://www.propain-bikes.com/en/product/bikes/freeride/spindrift-al-dual-crown/",
    verifiedAt: VERIFIED,
    verifiedBy: "FlowLine Editorial",
    safetyCritical: true,
  },
  {
    id: "cm-propain-rage-cf-frame",
    slot: "frame",
    manufacturer: "Propain",
    model: "Rage",
    variant: "CF",
    modelYear: 2025,
    attributes: [
      attr("rear_spacing", { enum: "157x12" }),
      attr("axle_rear", { enum: "12x157" }),
      attr("shock_eye_to_eye_mm", { num: 225, unit: "mm" }),
      attr("shock_stroke_mm", { num: 75, unit: "mm" }),
      attr("shock_mount_type", { enum: "trunnion" }),
      attr("headset_top", { enum: "ZS56" }),
      attr("headset_bottom", { enum: "ZS56" }),
      attr("bb_standard", { enum: "BSA83" }),
      attr("seatpost_diameter_mm", { num: 31.6, unit: "mm" }),
      attr("brake_mount_rear", { enum: "post_mount" }),
      attr("max_rotor_rear_mm", { num: 200, unit: "mm" }),
      attr("motor_interface", { enum: "n/a", text: "n/a" }),
      attr("wheel_size_rear", { enum: "29" }),
    ],
    adjusters: [],
    torqueSpecs: [],
    source: "oem",
    sourceUrl: "https://www.propain-bikes.com/en/product/bikes/downhill/rage-cf/",
    verifiedAt: VERIFIED,
    verifiedBy: "FlowLine Editorial",
    safetyCritical: true,
  },
  {
    id: "cm-propain-sresh-frame",
    slot: "frame",
    manufacturer: "Propain",
    model: "Sresh SL",
    variant: "CF TQ",
    modelYear: 2025,
    attributes: [
      attr("rear_spacing", { enum: "148x12_boost" }),
      attr("axle_rear", { enum: "12x148_boost" }),
      attr("shock_eye_to_eye_mm", { num: 210, unit: "mm" }),
      attr("shock_stroke_mm", { num: 55, unit: "mm" }),
      attr("shock_mount_type", { enum: "standard" }),
      attr("headset_top", { enum: "ZS56" }),
      attr("headset_bottom", { enum: "ZS56" }),
      attr("seatpost_diameter_mm", { num: 31.6, unit: "mm" }),
      attr("brake_mount_rear", { enum: "post_mount" }),
      attr("max_rotor_rear_mm", { num: 200, unit: "mm" }),
      attr("motor_interface", { enum: "tq_hpr60" }),
      attr("wheel_size_rear", { enum: "29" }),
    ],
    adjusters: [],
    torqueSpecs: [],
    source: "oem",
    sourceUrl: "https://www.propain-bikes.com/en/product/bikes/trail/sresh-sl/",
    verifiedAt: VERIFIED,
    verifiedBy: "FlowLine Editorial",
    safetyCritical: true,
  },
  {
    id: "cm-propain-ekano-enduro-frame",
    slot: "frame",
    manufacturer: "Propain",
    model: "Ekano AL Enduro",
    variant: "Avinox",
    modelYear: 2026,
    attributes: [
      attr("rear_spacing", { enum: "148x12_boost" }),
      attr("axle_rear", { enum: "12x148_boost" }),
      attr("shock_eye_to_eye_mm", { num: 210, unit: "mm" }),
      attr("shock_stroke_mm", { num: 55, unit: "mm" }),
      attr("shock_mount_type", { enum: "standard" }),
      attr("headset_top", { enum: "ZS56" }),
      attr("headset_bottom", { enum: "ZS56" }),
      attr("seatpost_diameter_mm", { num: 31.6, unit: "mm" }),
      attr("brake_mount_rear", { enum: "post_mount" }),
      attr("max_rotor_rear_mm", { num: 200, unit: "mm" }),
      attr("motor_interface", { enum: "dji_avinox" }),
      attr("wheel_size_rear", { enum: "27.5" }),
    ],
    adjusters: [],
    torqueSpecs: [],
    source: "oem",
    sourceUrl: "https://www.propain-bikes.com/en/product/bikes/enduro/ekano-al-enduro/",
    verifiedAt: VERIFIED,
    verifiedBy: "FlowLine Editorial",
    safetyCritical: true,
  },
  {
    id: "cm-propain-ekano-trail-frame",
    slot: "frame",
    manufacturer: "Propain",
    model: "Ekano AL Trail",
    variant: "Avinox",
    modelYear: 2026,
    attributes: [
      attr("rear_spacing", { enum: "148x12_boost" }),
      attr("axle_rear", { enum: "12x148_boost" }),
      attr("shock_eye_to_eye_mm", { num: 210, unit: "mm" }),
      attr("shock_stroke_mm", { num: 50, unit: "mm" }),
      attr("shock_mount_type", { enum: "standard" }),
      attr("headset_top", { enum: "ZS56" }),
      attr("headset_bottom", { enum: "ZS56" }),
      attr("seatpost_diameter_mm", { num: 31.6, unit: "mm" }),
      attr("brake_mount_rear", { enum: "post_mount" }),
      attr("max_rotor_rear_mm", { num: 200, unit: "mm" }),
      attr("motor_interface", { enum: "dji_avinox" }),
      attr("wheel_size_rear", { enum: "29" }),
    ],
    adjusters: [],
    torqueSpecs: [],
    source: "oem",
    sourceUrl: "https://www.propain-bikes.com/en/product/bikes/trail/ekano-al-trail/",
    verifiedAt: VERIFIED,
    verifiedBy: "FlowLine Editorial",
    safetyCritical: true,
  },
  {
    id: "cm-propain-terrel-frame",
    slot: "frame",
    manufacturer: "Propain",
    model: "Terrel",
    variant: "CF",
    modelYear: 2025,
    attributes: [
      attr("rear_spacing", { enum: "142x12" }),
      attr("axle_rear", { enum: "12x142" }),
      attr("headset_top", { enum: "IS52" }),
      attr("headset_bottom", { enum: "IS52" }),
      attr("bb_standard", { enum: "T47" }),
      attr("seatpost_diameter_mm", { num: 27.2, unit: "mm" }),
      attr("brake_mount_rear", { enum: "flat_mount" }),
      attr("max_rotor_rear_mm", { num: 160, unit: "mm" }),
      attr("max_tire_width_mm", { num: 50, unit: "mm" }),
      attr("motor_interface", { enum: "n/a", text: "n/a" }),
      attr("wheel_size_rear", { enum: "700c" }),
    ],
    adjusters: [],
    torqueSpecs: [],
    source: "oem",
    sourceUrl: "https://www.propain-bikes.com/en/product/bikes/gravel/terrel-cf/",
    verifiedAt: VERIFIED,
    verifiedBy: "FlowLine Editorial",
    safetyCritical: true,
  },
  part("cm-propain-terrel-fork", "fork", "Propain", "Terrel CF Fork", {
    variant: "Rigid 700c",
    url: "https://www.propain-bikes.com/en/product/bikes/gravel/terrel-cf/",
    safety: true,
    attrs: [
      attr("wheel_size", { enum: "700c" }),
      attr("brake_mount", { enum: "flat_mount" }),
    ],
  }),
  part("cm-acros-zs56-zs56", "headset", "Acros", "Stainless ZS56/ZS56", {
    url: "https://www.propain-bikes.com/en/product/bikes/enduro/tyee-al/",
    safety: true,
    attrs: [
      attr("headset_top", { enum: "ZS56" }),
      attr("headset_bottom", { enum: "ZS56" }),
    ],
  }),
  part("cm-rockshox-superdeluxe-21055-std", "rear_shock", "RockShox", "Super Deluxe", {
    variant: "210×55 Standard",
    year: 2025,
    url: "https://www.sram.com/en/rockshox",
    safety: true,
    attrs: [
      attr("eye_to_eye_mm", { num: 210, unit: "mm" }),
      attr("stroke_mm", { num: 55, unit: "mm" }),
      attr("mount_type", { enum: "standard" }),
    ],
  }),
  part("cm-rockshox-vivid-coil-23065-std", "rear_shock", "RockShox", "Vivid Coil Select", {
    variant: "230×65 Standard",
    year: 2025,
    url: "https://www.sram.com/en/rockshox",
    safety: true,
    attrs: [
      attr("eye_to_eye_mm", { num: 230, unit: "mm" }),
      attr("stroke_mm", { num: 65, unit: "mm" }),
      attr("mount_type", { enum: "standard" }),
    ],
  }),
  part("cm-fox-float-x-factory", "rear_shock", "Fox", "FLOAT X Factory", {
    url: "https://www.ridefox.com/",
    safety: true,
  }),
  part("cm-fox-dhx2-factory", "rear_shock", "Fox", "DHX2 Factory", {
    variant: "225×75 Trunnion",
    url: "https://www.ridefox.com/",
    safety: true,
    attrs: [
      attr("eye_to_eye_mm", { num: 225, unit: "mm" }),
      attr("stroke_mm", { num: 75, unit: "mm" }),
      attr("mount_type", { enum: "trunnion" }),
    ],
  }),
  part("cm-fox-36-factory-140", "fork", "Fox", "36 Factory Grip X2", {
    variant: "140mm 29",
    year: 2025,
    url: "https://www.ridefox.com/",
    safety: true,
    attrs: [
      attr("travel_mm", { num: 140, unit: "mm" }),
      attr("wheel_size", { enum: "29" }),
      attr("offset_mm", { num: 44, unit: "mm" }),
      attr("axle_front", { enum: "15x110_boost" }),
      attr("brake_mount", { enum: "post_mount" }),
    ],
  }),
  part("cm-rockshox-boxxer-200", "fork", "RockShox", "Boxxer Select", {
    variant: "200mm 29",
    year: 2025,
    url: "https://www.sram.com/en/rockshox",
    safety: true,
    attrs: [
      attr("travel_mm", { num: 200, unit: "mm" }),
      attr("wheel_size", { enum: "29" }),
      attr("offset_mm", { num: 46, unit: "mm" }),
      attr("axle_front", { enum: "20x110" }),
    ],
  }),
  part("cm-tq-hpr60", "motor", "TQ", "HPR60", {
    url: "https://www.tq-group.com/",
    safety: true,
    attrs: [
      attr("motor_system", { enum: "tq_hpr60" }),
      attr("max_torque_nm", { num: 60, unit: "Nm" }),
      attr("max_power_w", { num: 350, unit: "W" }),
    ],
  }),
  part("cm-tq-battery-360", "battery", "TQ", "HPR Battery V01", {
    variant: "360 Wh",
    url: "https://www.tq-group.com/",
    safety: true,
    attrs: [
      attr("capacity_wh", { num: 360, unit: "Wh" }),
      attr("battery_system", { enum: "tq_hpr60" }),
    ],
  }),
  part("cm-dji-avinox-m2", "motor", "DJI", "Avinox M2", {
    url: "https://www.propain-bikes.com/en/product/bikes/enduro/ekano-al-enduro/",
    safety: true,
    attrs: [
      attr("motor_system", { enum: "dji_avinox" }),
      attr("max_torque_nm", { num: 125, unit: "Nm" }),
      attr("max_power_w", { num: 1100, unit: "W" }),
    ],
  }),
  part("cm-avinox-battery-600", "battery", "DJI", "Avinox FS600", {
    variant: "600 Wh",
    url: "https://www.propain-bikes.com/en/product/bikes/enduro/ekano-al-enduro/",
    safety: true,
    attrs: [
      attr("capacity_wh", { num: 600, unit: "Wh" }),
      attr("battery_system", { enum: "dji_avinox" }),
    ],
  }),
  part("cm-avinox-dpc100", "display", "DJI", "Avinox DPC100", {
    url: "https://www.propain-bikes.com/en/product/bikes/enduro/ekano-al-enduro/",
    attrs: [attr("display_system", { enum: "dji_avinox" })],
  }),
];
