import type { ComponentModel, TypedAttribute } from "@/types/garage";
import { COMPONENT_CATALOG_DACH } from "./componentsDach";
import { COMPONENT_CATALOG_DACH_DEPTH } from "./componentsDachDepth";

const VERIFIED = "2026-05-14T00:00:00.000Z";

function attr(
  key: string,
  opts: {
    text?: string;
    num?: number;
    enum?: string;
    unit?: string;
    source?: TypedAttribute["source"];
  }
): TypedAttribute {
  return {
    key,
    valueText: opts.text,
    valueNum: opts.num,
    valueEnum: opts.enum ?? opts.text,
    unit: opts.unit,
    source: opts.source ?? "manufacturer_doc",
    verifiedAt: VERIFIED,
  };
}

/**
 * Redaktionell kuratierter Komponenten-Katalog (MVP-Seed + DACH-Enduro).
 * Quellen u. a.: BikeRadar Achsstandards, BIKE Magazin BB-Standards,
 * S.H.I.S. Headset-System, RockShox/Fox Service Docs, ETRTO-Praxis.
 */
const COMPONENT_CATALOG_CORE: ComponentModel[] = [
  // —— Gabeln ——
  {
    id: "cm-fox-36-factory-170",
    slot: "fork",
    manufacturer: "Fox",
    model: "36 Factory Grip2",
    variant: "170mm 29",
    modelYear: 2024,
    weightG: 2170,
    attributes: [
      attr("travel_mm", { num: 170, unit: "mm" }),
      attr("steerer_type", { enum: "tapered_1.5" }),
      attr("steerer_clamp_mm", { num: 28.6, unit: "mm" }),
      attr("crown_race_mm", { num: 40, unit: "mm" }),
      attr("axle_front", { enum: "15x110_boost" }),
      attr("brake_mount", { enum: "post_mount" }),
      attr("max_rotor_mm", { num: 230, unit: "mm" }),
      attr("wheel_size", { enum: "29" }),
      attr("offset_mm", { num: 44, unit: "mm" }),
    ],
    adjusters: [
      {
        key: "air_pressure_psi",
        label: "Luftdruck",
        unit: "psi",
        min: 40,
        max: 120,
        step: 1,
      },
      {
        key: "sag_pct",
        label: "SAG",
        unit: "%",
        min: 15,
        max: 35,
        step: 1,
      },
      {
        key: "rebound",
        label: "Zugstufe",
        unit: "clicks",
        totalClicks: 18,
        reference: "from_closed",
        min: 0,
        max: 18,
        step: 1,
      },
      {
        key: "lsc",
        label: "LSC",
        unit: "clicks",
        totalClicks: 16,
        reference: "from_closed",
        min: 0,
        max: 16,
        step: 1,
      },
      {
        key: "hsc",
        label: "HSC",
        unit: "clicks",
        totalClicks: 8,
        reference: "from_closed",
        min: 0,
        max: 8,
        step: 1,
      },
      {
        key: "tokens",
        label: "Volume Tokens",
        unit: "count",
        min: 0,
        max: 4,
        step: 1,
      },
    ],
    torqueSpecs: [
      {
        fastener: "Steckachse vorne",
        nm: 15,
        sourceUrl: "https://www.ridefox.com/",
        sourceLabel: "Fox Owner's Manual",
      },
    ],
    source: "manufacturer_doc",
    sourceUrl: "https://www.ridefox.com/",
    verifiedAt: VERIFIED,
    verifiedBy: "AetherRide Editorial",
    safetyCritical: true,
  },
  {
    id: "cm-rockshox-lyrik-160",
    slot: "fork",
    manufacturer: "RockShox",
    model: "Lyrik Ultimate",
    variant: "160mm 29",
    modelYear: 2024,
    weightG: 2050,
    attributes: [
      attr("travel_mm", { num: 160, unit: "mm" }),
      attr("steerer_type", { enum: "tapered_1.5" }),
      attr("steerer_clamp_mm", { num: 28.6, unit: "mm" }),
      attr("crown_race_mm", { num: 40, unit: "mm" }),
      attr("axle_front", { enum: "15x110_boost" }),
      attr("brake_mount", { enum: "post_mount" }),
      attr("max_rotor_mm", { num: 220, unit: "mm" }),
      attr("wheel_size", { enum: "29" }),
      attr("offset_mm", { num: 44, unit: "mm" }),
    ],
    adjusters: [
      {
        key: "air_pressure_psi",
        label: "Luftdruck",
        unit: "psi",
        min: 40,
        max: 120,
        step: 1,
      },
      {
        key: "sag_pct",
        label: "SAG",
        unit: "%",
        min: 15,
        max: 35,
        step: 1,
      },
      {
        key: "rebound",
        label: "Zugstufe",
        unit: "clicks",
        totalClicks: 18,
        reference: "from_closed",
        min: 0,
        max: 18,
        step: 1,
      },
      {
        key: "lsc",
        label: "LSC",
        unit: "clicks",
        totalClicks: 20,
        reference: "from_closed",
        min: 0,
        max: 20,
        step: 1,
      },
      {
        key: "hsc",
        label: "HSC",
        unit: "clicks",
        totalClicks: 10,
        reference: "from_closed",
        min: 0,
        max: 10,
        step: 1,
      },
    ],
    torqueSpecs: [
      {
        fastener: "Steckachse vorne",
        nm: 12,
        sourceUrl:
          "https://support.rockshox.com/hc/en-us/articles/4412306753947-How-often-should-I-service-my-RockShox-product",
        sourceLabel: "RockShox Service FAQ",
      },
    ],
    source: "manufacturer_doc",
    sourceUrl: "https://www.sram.com/en/rockshox",
    verifiedAt: VERIFIED,
    verifiedBy: "AetherRide Editorial",
    safetyCritical: true,
  },

  // —— Dämpfer ——
  {
    id: "cm-fox-float-x2-20565",
    slot: "rear_shock",
    manufacturer: "Fox",
    model: "Float X2 Factory",
    variant: "205×65 Trunnion",
    modelYear: 2024,
    attributes: [
      attr("eye_to_eye_mm", { num: 205, unit: "mm" }),
      attr("stroke_mm", { num: 65, unit: "mm" }),
      attr("mount_type", { enum: "trunnion" }),
      attr("hardware_width_mm", { num: 22.2, unit: "mm" }),
      attr("bushing_diameter_mm", { num: 8, unit: "mm" }),
    ],
    adjusters: [
      {
        key: "air_pressure_psi",
        label: "Luftdruck",
        unit: "psi",
        min: 100,
        max: 350,
        step: 5,
      },
      {
        key: "sag_pct",
        label: "SAG",
        unit: "%",
        min: 20,
        max: 40,
        step: 1,
      },
      {
        key: "rebound",
        label: "Zugstufe",
        unit: "clicks",
        totalClicks: 16,
        reference: "from_closed",
        min: 0,
        max: 16,
        step: 1,
      },
      {
        key: "lsc",
        label: "LSC",
        unit: "clicks",
        totalClicks: 16,
        reference: "from_closed",
        min: 0,
        max: 16,
        step: 1,
      },
      {
        key: "hsc",
        label: "HSC",
        unit: "clicks",
        totalClicks: 8,
        reference: "from_closed",
        min: 0,
        max: 8,
        step: 1,
      },
    ],
    torqueSpecs: [],
    source: "manufacturer_doc",
    sourceUrl: "https://www.ridefox.com/",
    verifiedAt: VERIFIED,
    verifiedBy: "AetherRide Editorial",
    safetyCritical: true,
  },
  {
    id: "cm-rockshox-superdeluxe-23065",
    slot: "rear_shock",
    manufacturer: "RockShox",
    model: "Super Deluxe Ultimate",
    variant: "230×65 Standard",
    modelYear: 2024,
    attributes: [
      attr("eye_to_eye_mm", { num: 230, unit: "mm" }),
      attr("stroke_mm", { num: 65, unit: "mm" }),
      attr("mount_type", { enum: "standard" }),
      attr("hardware_width_mm", { num: 22.2, unit: "mm" }),
      attr("bushing_diameter_mm", { num: 8, unit: "mm" }),
    ],
    adjusters: [
      {
        key: "air_pressure_psi",
        label: "Luftdruck",
        unit: "psi",
        min: 100,
        max: 350,
        step: 5,
      },
      {
        key: "sag_pct",
        label: "SAG",
        unit: "%",
        min: 20,
        max: 40,
        step: 1,
      },
      {
        key: "rebound",
        label: "Zugstufe",
        unit: "clicks",
        totalClicks: 14,
        reference: "from_closed",
        min: 0,
        max: 14,
        step: 1,
      },
      {
        key: "lsc",
        label: "LSC",
        unit: "clicks",
        totalClicks: 18,
        reference: "from_closed",
        min: 0,
        max: 18,
        step: 1,
      },
    ],
    torqueSpecs: [],
    source: "manufacturer_doc",
    sourceUrl: "https://www.sram.com/en/rockshox",
    verifiedAt: VERIFIED,
    verifiedBy: "AetherRide Editorial",
    safetyCritical: true,
  },

  // —— Rahmen (als ComponentModel für Interface-Attribute) ——
  {
    id: "cm-transition-spire-frame",
    slot: "frame",
    manufacturer: "Transition",
    model: "Spire",
    variant: "Carbon",
    modelYear: 2024,
    attributes: [
      attr("rear_spacing", { enum: "148x12_boost" }),
      attr("axle_rear", { enum: "12x148_boost" }),
      attr("shock_eye_to_eye_mm", { num: 205, unit: "mm" }),
      attr("shock_stroke_mm", { num: 65, unit: "mm" }),
      attr("shock_mount_type", { enum: "trunnion" }),
      attr("headset_top", { enum: "ZS44" }),
      attr("headset_bottom", { enum: "ZS56" }),
      attr("bb_standard", { enum: "BSA73" }),
      attr("seatpost_diameter_mm", { num: 31.6, unit: "mm" }),
      attr("max_seatpost_insertion_mm", { num: 250, unit: "mm" }),
      attr("brake_mount_rear", { enum: "post_mount" }),
      attr("max_rotor_rear_mm", { num: 203, unit: "mm" }),
      attr("max_tire_width_mm", { num: 66, unit: "mm" }),
      attr("motor_interface", { enum: "n/a", text: "n/a" }),
      attr("wheel_size_rear", { enum: "29" }),
    ],
    adjusters: [],
    torqueSpecs: [
      {
        fastener: "Vorbauschrauben",
        nm: 5.5,
        sourceUrl: "https://www.transitionbikes.com/",
        sourceLabel: "Transition Owner's Manual",
      },
    ],
    source: "oem",
    sourceUrl: "https://www.transitionbikes.com/",
    verifiedAt: VERIFIED,
    verifiedBy: "AetherRide Editorial",
    safetyCritical: true,
  },
  {
    id: "cm-specialized-diverge-frame",
    slot: "frame",
    manufacturer: "Specialized",
    model: "Diverge",
    variant: "Carbon",
    modelYear: 2023,
    attributes: [
      attr("rear_spacing", { enum: "142x12" }),
      attr("axle_rear", { enum: "12x142" }),
      attr("headset_top", { enum: "IS42" }),
      attr("headset_bottom", { enum: "IS52" }),
      attr("bb_standard", { enum: "BB30" }),
      attr("seatpost_diameter_mm", { num: 27.2, unit: "mm" }),
      attr("max_seatpost_insertion_mm", { num: 220, unit: "mm" }),
      attr("brake_mount_rear", { enum: "flat_mount" }),
      attr("max_rotor_rear_mm", { num: 160, unit: "mm" }),
      attr("max_tire_width_mm", { num: 47, unit: "mm" }),
      attr("motor_interface", { enum: "n/a", text: "n/a" }),
      attr("wheel_size_rear", { enum: "700c" }),
    ],
    adjusters: [],
    torqueSpecs: [],
    source: "oem",
    sourceUrl: "https://www.specialized.com/",
    verifiedAt: VERIFIED,
    verifiedBy: "AetherRide Editorial",
    safetyCritical: true,
  },
  {
    id: "cm-canyon-spectralon-cf-frame",
    slot: "frame",
    manufacturer: "Canyon",
    model: "Spectral:ON CF",
    variant: "E-MTB",
    modelYear: 2024,
    attributes: [
      attr("rear_spacing", { enum: "148x12_boost" }),
      attr("axle_rear", { enum: "12x148_boost" }),
      attr("shock_eye_to_eye_mm", { num: 230, unit: "mm" }),
      attr("shock_stroke_mm", { num: 65, unit: "mm" }),
      attr("shock_mount_type", { enum: "standard" }),
      attr("headset_top", { enum: "ZS44" }),
      attr("headset_bottom", { enum: "ZS56" }),
      attr("bb_standard", { enum: "BSA73" }),
      attr("seatpost_diameter_mm", { num: 34.9, unit: "mm" }),
      attr("max_seatpost_insertion_mm", { num: 260, unit: "mm" }),
      attr("brake_mount_rear", { enum: "post_mount" }),
      attr("max_rotor_rear_mm", { num: 220, unit: "mm" }),
      attr("max_tire_width_mm", { num: 66, unit: "mm" }),
      attr("motor_interface", { enum: "bosch_smart_system" }),
      attr("wheel_size_rear", { enum: "29" }),
    ],
    adjusters: [],
    torqueSpecs: [],
    source: "oem",
    sourceUrl: "https://www.canyon.com/",
    verifiedAt: VERIFIED,
    verifiedBy: "AetherRide Editorial",
    safetyCritical: true,
  },

  // —— Steuersatz / Cockpit ——
  {
    id: "cm-cane-creek-zs44-zs56",
    slot: "headset",
    manufacturer: "Cane Creek",
    model: "40",
    variant: "ZS44/28.6 · ZS56/40",
    attributes: [
      attr("headset_top", { enum: "ZS44" }),
      attr("headset_bottom", { enum: "ZS56" }),
      attr("steerer_type", { enum: "tapered_1.5" }),
    ],
    adjusters: [],
    torqueSpecs: [],
    source: "manufacturer_doc",
    sourceUrl:
      "https://www.mountainflyermagazine.com/img/upimages/standardized_headset_identification_system.pdf",
    verifiedAt: VERIFIED,
    verifiedBy: "AetherRide Editorial",
    safetyCritical: true,
  },
  {
    id: "cm-renthal-apex-35",
    slot: "stem",
    manufacturer: "Renthal",
    model: "Apex",
    variant: "35mm Clamp · 40mm",
    attributes: [
      attr("stem_clamp_mm", { enum: "35.0", num: 35, unit: "mm" }),
      attr("steerer_clamp_mm", { num: 28.6, unit: "mm" }),
      attr("length_mm", { num: 40, unit: "mm" }),
    ],
    adjusters: [],
    torqueSpecs: [
      {
        fastener: "Lenkerklemmung",
        nm: 5,
        sourceUrl: "https://www.renthal.com/",
        sourceLabel: "Renthal Tech Spec",
      },
    ],
    source: "manufacturer_doc",
    sourceUrl: "https://www.renthal.com/",
    verifiedAt: VERIFIED,
    verifiedBy: "AetherRide Editorial",
    safetyCritical: true,
  },
  {
    id: "cm-renthal-fatbar-35",
    slot: "handlebar",
    manufacturer: "Renthal",
    model: "Fatbar Carbon",
    variant: "35mm · 800mm",
    attributes: [
      attr("handlebar_clamp_mm", { enum: "35.0", num: 35, unit: "mm" }),
      attr("width_mm", { num: 800, unit: "mm" }),
      attr("rise_mm", { num: 20, unit: "mm" }),
    ],
    adjusters: [
      {
        key: "width_mm",
        label: "Breite",
        unit: "mm",
        min: 740,
        max: 800,
        step: 5,
      },
    ],
    torqueSpecs: [],
    source: "manufacturer_doc",
    sourceUrl: "https://www.renthal.com/",
    verifiedAt: VERIFIED,
    verifiedBy: "AetherRide Editorial",
    safetyCritical: true,
  },
  {
    id: "cm-oneup-v3-dropper-34-9",
    slot: "seatpost",
    manufacturer: "OneUp",
    model: "V3 Dropper",
    variant: "34.9 · 210mm",
    attributes: [
      attr("seatpost_diameter_mm", { num: 34.9, unit: "mm" }),
      attr("dropper_travel_mm", { num: 210, unit: "mm" }),
      attr("min_insertion_mm", { num: 140, unit: "mm" }),
    ],
    adjusters: [
      {
        key: "saddle_height_mm",
        label: "Sattelhöhe",
        unit: "mm",
        min: 600,
        max: 820,
        step: 1,
      },
    ],
    torqueSpecs: [
      {
        fastener: "Sattelstützenklemmung",
        nm: 6,
        sourceUrl: "https://oneupcomponents.com/",
        sourceLabel: "OneUp Manual",
      },
    ],
    source: "manufacturer_doc",
    sourceUrl: "https://oneupcomponents.com/",
    verifiedAt: VERIFIED,
    verifiedBy: "AetherRide Editorial",
    safetyCritical: true,
  },
  {
    id: "cm-oneup-v3-dropper-31-6",
    slot: "seatpost",
    manufacturer: "OneUp",
    model: "V3 Dropper",
    variant: "31.6 · 210mm",
    attributes: [
      attr("seatpost_diameter_mm", { num: 31.6, unit: "mm" }),
      attr("dropper_travel_mm", { num: 210, unit: "mm" }),
      attr("min_insertion_mm", { num: 140, unit: "mm" }),
    ],
    adjusters: [
      {
        key: "saddle_height_mm",
        label: "Sattelhöhe",
        unit: "mm",
        min: 600,
        max: 820,
        step: 1,
      },
    ],
    torqueSpecs: [
      {
        fastener: "Sattelstützenklemmung",
        nm: 6,
        sourceUrl: "https://oneupcomponents.com/",
        sourceLabel: "OneUp Manual",
      },
    ],
    source: "manufacturer_doc",
    sourceUrl: "https://oneupcomponents.com/",
    verifiedAt: VERIFIED,
    verifiedBy: "AetherRide Editorial",
    safetyCritical: true,
  },

  // —— Laufräder / Naben / Felgen ——
  {
    id: "cm-dt-350-boost-front",
    slot: "front_hub",
    manufacturer: "DT Swiss",
    model: "350",
    variant: "15×110 Boost Center Lock",
    attributes: [
      attr("axle_front", { enum: "15x110_boost" }),
      attr("rotor_mount", { enum: "center_lock" }),
    ],
    adjusters: [],
    torqueSpecs: [],
    source: "manufacturer_doc",
    sourceUrl: "https://www.dtswiss.com/",
    verifiedAt: VERIFIED,
    verifiedBy: "AetherRide Editorial",
    safetyCritical: true,
  },
  {
    id: "cm-dt-350-boost-rear-xd",
    slot: "rear_hub",
    manufacturer: "DT Swiss",
    model: "350",
    variant: "12×148 Boost · XD",
    attributes: [
      attr("axle_rear", { enum: "12x148_boost" }),
      attr("rear_spacing", { enum: "148x12_boost" }),
      attr("freehub_standard", { enum: "XD" }),
      attr("rotor_mount", { enum: "center_lock" }),
    ],
    adjusters: [],
    torqueSpecs: [],
    source: "manufacturer_doc",
    sourceUrl: "https://www.dtswiss.com/",
    verifiedAt: VERIFIED,
    verifiedBy: "AetherRide Editorial",
    safetyCritical: true,
  },
  {
    id: "cm-dt-350-boost-rear-ms",
    slot: "rear_hub",
    manufacturer: "DT Swiss",
    model: "350",
    variant: "12×148 Boost · Micro Spline",
    attributes: [
      attr("axle_rear", { enum: "12x148_boost" }),
      attr("rear_spacing", { enum: "148x12_boost" }),
      attr("freehub_standard", { enum: "MicroSpline" }),
      attr("rotor_mount", { enum: "center_lock" }),
    ],
    adjusters: [],
    torqueSpecs: [],
    source: "manufacturer_doc",
    sourceUrl: "https://www.dtswiss.com/",
    verifiedAt: VERIFIED,
    verifiedBy: "AetherRide Editorial",
    safetyCritical: true,
  },
  {
    id: "cm-dt-xm1700-rim-front",
    slot: "front_rim",
    manufacturer: "DT Swiss",
    model: "XM 1700 Spline",
    variant: "30mm IRW 29",
    attributes: [
      attr("internal_rim_width_mm", { num: 30, unit: "mm" }),
      attr("wheel_size", { enum: "29" }),
      attr("tubeless_ready", { enum: "yes" }),
    ],
    adjusters: [],
    torqueSpecs: [],
    source: "manufacturer_doc",
    sourceUrl: "https://www.dtswiss.com/",
    verifiedAt: VERIFIED,
    verifiedBy: "AetherRide Editorial",
    safetyCritical: true,
  },
  {
    id: "cm-dt-xm1700-rim-rear",
    slot: "rear_rim",
    manufacturer: "DT Swiss",
    model: "XM 1700 Spline",
    variant: "30mm IRW 29",
    attributes: [
      attr("internal_rim_width_mm", { num: 30, unit: "mm" }),
      attr("wheel_size", { enum: "29" }),
      attr("tubeless_ready", { enum: "yes" }),
    ],
    adjusters: [],
    torqueSpecs: [],
    source: "manufacturer_doc",
    sourceUrl: "https://www.dtswiss.com/",
    verifiedAt: VERIFIED,
    verifiedBy: "AetherRide Editorial",
    safetyCritical: true,
  },

  // —— Reifen ——
  {
    id: "cm-maxxis-assegai-29-25",
    slot: "tire_front",
    manufacturer: "Maxxis",
    model: "Assegai",
    variant: "29×2.5 WT MaxxGrip DD",
    attributes: [
      attr("tire_width_in", { num: 2.5 }),
      attr("tire_width_mm", { num: 63.5, unit: "mm" }),
      attr("etrto", { text: "63-622" }),
      attr("wheel_size", { enum: "29" }),
      attr("compound", { text: "MaxxGrip" }),
      attr("casing", { text: "DD" }),
    ],
    adjusters: [
      {
        key: "pressure_psi",
        label: "Druck",
        unit: "psi",
        min: 15,
        max: 35,
        step: 0.5,
      },
    ],
    torqueSpecs: [],
    source: "manufacturer_doc",
    sourceUrl: "https://www.maxxis.com/",
    verifiedAt: VERIFIED,
    verifiedBy: "AetherRide Editorial",
    safetyCritical: true,
  },
  {
    id: "cm-maxxis-dhr2-29-24",
    slot: "tire_rear",
    manufacturer: "Maxxis",
    model: "Minion DHR II",
    variant: "29×2.4 WT MaxxTerra DD",
    attributes: [
      attr("tire_width_in", { num: 2.4 }),
      attr("tire_width_mm", { num: 61, unit: "mm" }),
      attr("etrto", { text: "61-622" }),
      attr("wheel_size", { enum: "29" }),
      attr("compound", { text: "MaxxTerra" }),
      attr("casing", { text: "DD" }),
    ],
    adjusters: [
      {
        key: "pressure_psi",
        label: "Druck",
        unit: "psi",
        min: 15,
        max: 35,
        step: 0.5,
      },
    ],
    torqueSpecs: [],
    source: "manufacturer_doc",
    sourceUrl: "https://www.maxxis.com/",
    verifiedAt: VERIFIED,
    verifiedBy: "AetherRide Editorial",
    safetyCritical: true,
  },
  {
    id: "cm-pathfinder-pro-700-42",
    slot: "tire_front",
    manufacturer: "Specialized",
    model: "Pathfinder Pro",
    variant: "700×42",
    attributes: [
      attr("tire_width_in", { num: 1.65 }),
      attr("tire_width_mm", { num: 42, unit: "mm" }),
      attr("etrto", { text: "42-622" }),
      attr("wheel_size", { enum: "700c" }),
    ],
    adjusters: [
      {
        key: "pressure_psi",
        label: "Druck",
        unit: "psi",
        min: 28,
        max: 55,
        step: 1,
      },
    ],
    torqueSpecs: [],
    source: "oem",
    sourceUrl: "https://www.specialized.com/",
    verifiedAt: VERIFIED,
    verifiedBy: "AetherRide Editorial",
    safetyCritical: true,
  },

  // —— Antrieb ——
  {
    id: "cm-sram-x0-cassette-xd",
    slot: "cassette",
    manufacturer: "SRAM",
    model: "X0 Eagle Transmission",
    variant: "10-52 · XD",
    attributes: [
      attr("freehub_standard", { enum: "XD" }),
      attr("speeds", { num: 12 }),
      attr("range", { text: "10-52" }),
    ],
    adjusters: [],
    torqueSpecs: [],
    source: "manufacturer_doc",
    sourceUrl: "https://www.sram.com/",
    verifiedAt: VERIFIED,
    verifiedBy: "AetherRide Editorial",
    safetyCritical: false,
  },
  {
    id: "cm-shimano-xt-cassette-ms",
    slot: "cassette",
    manufacturer: "Shimano",
    model: "XT M8100",
    variant: "10-51 · Micro Spline",
    attributes: [
      attr("freehub_standard", { enum: "MicroSpline" }),
      attr("speeds", { num: 12 }),
      attr("range", { text: "10-51" }),
    ],
    adjusters: [],
    torqueSpecs: [],
    source: "manufacturer_doc",
    sourceUrl: "https://bike.shimano.com/",
    verifiedAt: VERIFIED,
    verifiedBy: "AetherRide Editorial",
    safetyCritical: false,
  },
  {
    id: "cm-sram-dub-bsa73",
    slot: "bottom_bracket",
    manufacturer: "SRAM",
    model: "DUB BSA",
    variant: "73mm",
    attributes: [
      attr("bb_standard", { enum: "BSA73" }),
      attr("crank_axle", { enum: "DUB_28.99" }),
    ],
    adjusters: [],
    torqueSpecs: [],
    source: "manufacturer_doc",
    sourceUrl:
      "https://www.bike-magazin.de/en/workshop/circuit-or-drive/mountain-bike-bottom-bracket-standards-an-overview-of-the-utter-chaos/",
    verifiedAt: VERIFIED,
    verifiedBy: "AetherRide Editorial",
    safetyCritical: false,
  },
  {
    id: "cm-sram-x0-crank-dub",
    slot: "crankset",
    manufacturer: "SRAM",
    model: "X0 Eagle Transmission",
    variant: "DUB 170mm",
    attributes: [
      attr("crank_axle", { enum: "DUB_28.99" }),
      attr("crank_length_mm", { num: 170, unit: "mm" }),
      attr("chainring_bcd", { enum: "direct_mount" }),
    ],
    adjusters: [],
    torqueSpecs: [],
    source: "manufacturer_doc",
    sourceUrl: "https://www.sram.com/",
    verifiedAt: VERIFIED,
    verifiedBy: "AetherRide Editorial",
    safetyCritical: false,
  },
  {
    id: "cm-sram-x0-chainring-32",
    slot: "chainring",
    manufacturer: "SRAM",
    model: "X0 T-Type",
    variant: "32t",
    attributes: [
      attr("chainring_teeth", { num: 32 }),
      attr("chainline_boost", { enum: "yes" }),
      attr("chainring_bcd", { enum: "direct_mount" }),
    ],
    adjusters: [],
    torqueSpecs: [],
    source: "manufacturer_doc",
    sourceUrl: "https://www.sram.com/",
    verifiedAt: VERIFIED,
    verifiedBy: "AetherRide Editorial",
    safetyCritical: false,
  },
  {
    id: "cm-sram-gx-chain",
    slot: "chain",
    manufacturer: "SRAM",
    model: "GX Eagle Transmission",
    variant: "12s Flattop",
    attributes: [attr("speeds", { num: 12 })],
    adjusters: [],
    torqueSpecs: [],
    source: "manufacturer_doc",
    sourceUrl: "https://www.sram.com/",
    verifiedAt: VERIFIED,
    verifiedBy: "AetherRide Editorial",
    safetyCritical: false,
  },
  {
    id: "cm-sram-x0-rd",
    slot: "rear_derailleur",
    manufacturer: "SRAM",
    model: "X0 Eagle Transmission",
    variant: "T-Type",
    attributes: [attr("speeds", { num: 12 })],
    adjusters: [],
    torqueSpecs: [],
    source: "manufacturer_doc",
    sourceUrl: "https://www.sram.com/",
    verifiedAt: VERIFIED,
    verifiedBy: "AetherRide Editorial",
    safetyCritical: false,
  },
  {
    id: "cm-sram-pod-controller",
    slot: "shifter",
    manufacturer: "SRAM",
    model: "Pod Ultimate",
    variant: "T-Type",
    attributes: [attr("speeds", { num: 12 })],
    adjusters: [],
    torqueSpecs: [],
    source: "manufacturer_doc",
    sourceUrl: "https://www.sram.com/",
    verifiedAt: VERIFIED,
    verifiedBy: "AetherRide Editorial",
    safetyCritical: false,
  },

  // —— Bremsen ——
  {
    id: "cm-sram-code-rsc-front",
    slot: "brake_front",
    manufacturer: "SRAM",
    model: "Code RSC",
    variant: "Post Mount",
    attributes: [
      attr("brake_mount", { enum: "post_mount" }),
      attr("rotor_mount", { enum: "center_lock" }),
    ],
    adjusters: [
      {
        key: "lever_reach",
        label: "Hebelreichweite",
        unit: "clicks",
        min: 0,
        max: 10,
        step: 1,
      },
    ],
    torqueSpecs: [
      {
        fastener: "Bremssattel Post Mount",
        nm: 9,
        sourceUrl: "https://www.sram.com/",
        sourceLabel: "SRAM Brake Manual",
      },
    ],
    source: "manufacturer_doc",
    sourceUrl: "https://www.sram.com/",
    verifiedAt: VERIFIED,
    verifiedBy: "AetherRide Editorial",
    safetyCritical: true,
  },
  {
    id: "cm-sram-code-rsc-rear",
    slot: "brake_rear",
    manufacturer: "SRAM",
    model: "Code RSC",
    variant: "Post Mount",
    attributes: [
      attr("brake_mount", { enum: "post_mount" }),
      attr("rotor_mount", { enum: "center_lock" }),
    ],
    adjusters: [],
    torqueSpecs: [
      {
        fastener: "Bremssattel Post Mount",
        nm: 9,
        sourceUrl: "https://www.sram.com/",
        sourceLabel: "SRAM Brake Manual",
      },
    ],
    source: "manufacturer_doc",
    sourceUrl: "https://www.sram.com/",
    verifiedAt: VERIFIED,
    verifiedBy: "AetherRide Editorial",
    safetyCritical: true,
  },
  {
    id: "cm-sram-hs2-200-front",
    slot: "rotor_front",
    manufacturer: "SRAM",
    model: "HS2",
    variant: "200mm Center Lock",
    attributes: [
      attr("rotor_diameter_mm", { num: 200, unit: "mm" }),
      attr("rotor_mount", { enum: "center_lock" }),
    ],
    adjusters: [],
    torqueSpecs: [],
    source: "manufacturer_doc",
    sourceUrl: "https://www.sram.com/",
    verifiedAt: VERIFIED,
    verifiedBy: "AetherRide Editorial",
    safetyCritical: true,
  },
  {
    id: "cm-sram-hs2-180-rear",
    slot: "rotor_rear",
    manufacturer: "SRAM",
    model: "HS2",
    variant: "180mm Center Lock",
    attributes: [
      attr("rotor_diameter_mm", { num: 180, unit: "mm" }),
      attr("rotor_mount", { enum: "center_lock" }),
    ],
    adjusters: [],
    torqueSpecs: [],
    source: "manufacturer_doc",
    sourceUrl: "https://www.sram.com/",
    verifiedAt: VERIFIED,
    verifiedBy: "AetherRide Editorial",
    safetyCritical: true,
  },
  {
    id: "cm-sram-organic-pads",
    slot: "brake_pads_front",
    manufacturer: "SRAM",
    model: "Organic",
    variant: "Code",
    attributes: [attr("pad_compound", { enum: "organic" })],
    adjusters: [],
    torqueSpecs: [],
    source: "manufacturer_doc",
    sourceUrl: "https://www.sram.com/",
    verifiedAt: VERIFIED,
    verifiedBy: "AetherRide Editorial",
    safetyCritical: true,
  },
  {
    id: "cm-sram-organic-pads-rear",
    slot: "brake_pads_rear",
    manufacturer: "SRAM",
    model: "Organic",
    variant: "Code",
    attributes: [attr("pad_compound", { enum: "organic" })],
    adjusters: [],
    torqueSpecs: [],
    source: "manufacturer_doc",
    sourceUrl: "https://www.sram.com/",
    verifiedAt: VERIFIED,
    verifiedBy: "AetherRide Editorial",
    safetyCritical: true,
  },

  // —— E-Bike ——
  {
    id: "cm-bosch-cx-gen5",
    slot: "motor",
    manufacturer: "Bosch",
    model: "Performance Line CX",
    variant: "Gen5 Smart System",
    attributes: [
      attr("motor_interface", { enum: "bosch_smart_system" }),
      attr("max_torque_nm", { num: 85, unit: "Nm" }),
      attr("system", { text: "Smart System" }),
    ],
    adjusters: [],
    torqueSpecs: [],
    source: "manufacturer_doc",
    sourceUrl: "https://www.bosch-ebike.com/",
    verifiedAt: VERIFIED,
    verifiedBy: "AetherRide Editorial",
    safetyCritical: true,
  },
  {
    id: "cm-bosch-powertube-800",
    slot: "battery",
    manufacturer: "Bosch",
    model: "PowerTube",
    variant: "800 Wh",
    attributes: [
      attr("capacity_wh", { num: 800, unit: "Wh" }),
      attr("motor_interface", { enum: "bosch_smart_system" }),
    ],
    adjusters: [],
    torqueSpecs: [],
    source: "manufacturer_doc",
    sourceUrl: "https://www.bosch-ebike.com/",
    verifiedAt: VERIFIED,
    verifiedBy: "AetherRide Editorial",
    safetyCritical: false,
  },
  {
    id: "cm-bosch-kiox-300",
    slot: "display",
    manufacturer: "Bosch",
    model: "Kiox 300",
    variant: "Smart System",
    attributes: [attr("motor_interface", { enum: "bosch_smart_system" })],
    adjusters: [],
    torqueSpecs: [],
    source: "manufacturer_doc",
    sourceUrl: "https://www.bosch-ebike.com/",
    verifiedAt: VERIFIED,
    verifiedBy: "AetherRide Editorial",
    safetyCritical: false,
  },

  // —— Sonstiges ——
  {
    id: "cm-sdg-belair",
    slot: "saddle",
    manufacturer: "SDG",
    model: "Bel-Air V3",
    attributes: [],
    adjusters: [
      {
        key: "setback_mm",
        label: "Versatz",
        unit: "mm",
        min: -20,
        max: 20,
        step: 1,
      },
    ],
    torqueSpecs: [],
    source: "editorial",
    sourceUrl: "https://www.sdgcomponents.com/",
    verifiedAt: VERIFIED,
    verifiedBy: "AetherRide Editorial",
    safetyCritical: false,
  },
  {
    id: "cm-odey-grips",
    slot: "grips",
    manufacturer: "ODI",
    model: "Elite Pro",
    attributes: [],
    adjusters: [],
    torqueSpecs: [],
    source: "editorial",
    sourceUrl: "https://odigrips.com/",
    verifiedAt: VERIFIED,
    verifiedBy: "AetherRide Editorial",
    safetyCritical: false,
  },
  {
    id: "cm-ht-components-pedals",
    slot: "pedals",
    manufacturer: "HT",
    model: "ME03",
    attributes: [],
    adjusters: [],
    torqueSpecs: [
      {
        fastener: "Pedalachse",
        nm: 35,
        sourceUrl: "https://ht-components.com/",
        sourceLabel: "HT Manual",
      },
    ],
    source: "manufacturer_doc",
    sourceUrl: "https://ht-components.com/",
    verifiedAt: VERIFIED,
    verifiedBy: "AetherRide Editorial",
    safetyCritical: false,
  },
];

export const COMPONENT_CATALOG: ComponentModel[] = [
  ...COMPONENT_CATALOG_CORE,
  ...COMPONENT_CATALOG_DACH,
  ...COMPONENT_CATALOG_DACH_DEPTH,
];

export function getComponentModel(id: string): ComponentModel | undefined {
  return COMPONENT_CATALOG.find((c) => c.id === id);
}

export function listComponentModels(slot?: import("@/types/garage").ComponentSlot) {
  return slot
    ? COMPONENT_CATALOG.filter((c) => c.slot === slot)
    : COMPONENT_CATALOG;
}

export function modelDisplayName(m: ComponentModel): string {
  return [m.manufacturer, m.model, m.variant].filter(Boolean).join(" ");
}
