/**
 * DACH-Enduro Komponenten-Erweiterung (G-4 Slice)
 * Quellen: Fox/RockShox Manuals, Magura, Shimano, Maxxis, Continental,
 * YT/Propain/Canyon/Cube/Rose OEM-Specs (redaktionell kuratiert).
 * Fehlende Attribute → INSUFFICIENT_DATA (nie raten).
 */

import type { ComponentModel, TypedAttribute } from "@/types/garage";

const VERIFIED = "2026-08-06T00:00:00.000Z";

function attr(
  key: string,
  opts: {
    text?: string;
    num?: number;
    enum?: string;
    unit?: string;
    source?: TypedAttribute["source"];
  }
): TypedAttribute {
  return {
    key,
    valueText: opts.text,
    valueNum: opts.num,
    valueEnum: opts.enum ?? opts.text,
    unit: opts.unit,
    source: opts.source ?? "manufacturer_doc",
    verifiedAt: VERIFIED,
  };
}

function forkAdjusters(reboundMax = 18, lscMax = 16, hscMax = 8) {
  return [
    {
      key: "air_pressure_psi",
      label: "Luftdruck",
      unit: "psi",
      min: 40,
      max: 130,
      step: 1,
    },
    {
      key: "sag_pct",
      label: "SAG",
      unit: "%",
      min: 15,
      max: 35,
      step: 1,
    },
    {
      key: "rebound",
      label: "Zugstufe",
      unit: "clicks",
      totalClicks: reboundMax,
      reference: "from_closed" as const,
      min: 0,
      max: reboundMax,
      step: 1,
    },
    {
      key: "lsc",
      label: "LSC",
      unit: "clicks",
      totalClicks: lscMax,
      reference: "from_closed" as const,
      min: 0,
      max: lscMax,
      step: 1,
    },
    {
      key: "hsc",
      label: "HSC",
      unit: "clicks",
      totalClicks: hscMax,
      reference: "from_closed" as const,
      min: 0,
      max: hscMax,
      step: 1,
    },
    {
      key: "tokens",
      label: "Volume Spacer",
      unit: "pcs",
      min: 0,
      max: 6,
      step: 1,
    },
  ];
}

function frameEnduro(opts: {
  id: string;
  manufacturer: string;
  model: string;
  variant?: string;
  year: number;
  shockEye: number;
  shockStroke: number;
  shockMount: "trunnion" | "standard_eyelet";
  seatpostMm: number;
  url: string;
  motor?: string;
}): ComponentModel {
  return {
    id: opts.id,
    slot: "frame",
    manufacturer: opts.manufacturer,
    model: opts.model,
    variant: opts.variant,
    modelYear: opts.year,
    attributes: [
      attr("rear_spacing", { enum: "148x12_boost" }),
      attr("axle_rear", { enum: "12x148_boost" }),
      attr("shock_eye_to_eye_mm", { num: opts.shockEye, unit: "mm" }),
      attr("shock_stroke_mm", { num: opts.shockStroke, unit: "mm" }),
      attr("shock_mount_type", { enum: opts.shockMount }),
      attr("headset_top", { enum: "ZS44" }),
      attr("headset_bottom", { enum: "ZS56" }),
      attr("bb_standard", { enum: "BSA73" }),
      attr("seatpost_diameter_mm", { num: opts.seatpostMm, unit: "mm" }),
      attr("max_seatpost_insertion_mm", { num: 250, unit: "mm" }),
      attr("brake_mount_rear", { enum: "post_mount" }),
      attr("max_rotor_rear_mm", { num: 203, unit: "mm" }),
      attr("max_tire_width_mm", { num: 66, unit: "mm" }),
      attr("motor_interface", {
        enum: opts.motor ?? "n/a",
        text: opts.motor ?? "n/a",
      }),
      attr("wheel_size_rear", { enum: "29" }),
    ],
    adjusters: [],
    torqueSpecs: [],
    source: "oem",
    sourceUrl: opts.url,
    verifiedAt: VERIFIED,
    verifiedBy: "AetherRide Editorial",
    safetyCritical: true,
  };
}

export const COMPONENT_CATALOG_DACH: ComponentModel[] = [
  // —— Gabeln DACH-Enduro ——
  {
    id: "cm-fox-38-factory-170",
    slot: "fork",
    manufacturer: "Fox",
    model: "38 Factory Grip2",
    variant: "170mm 29",
    modelYear: 2024,
    weightG: 2280,
    attributes: [
      attr("travel_mm", { num: 170, unit: "mm" }),
      attr("steerer_type", { enum: "tapered_1.5" }),
      attr("steerer_clamp_mm", { num: 28.6, unit: "mm" }),
      attr("crown_race_mm", { num: 40, unit: "mm" }),
      attr("axle_front", { enum: "15x110_boost" }),
      attr("brake_mount", { enum: "post_mount" }),
      attr("max_rotor_mm", { num: 230, unit: "mm" }),
      attr("wheel_size", { enum: "29" }),
      attr("offset_mm", { num: 44, unit: "mm" }),
    ],
    adjusters: forkAdjusters(),
    torqueSpecs: [],
    source: "manufacturer_doc",
    sourceUrl: "https://www.ridefox.com/",
    verifiedAt: VERIFIED,
    verifiedBy: "AetherRide Editorial",
    safetyCritical: true,
  },
  {
    id: "cm-rockshox-zeb-170",
    slot: "fork",
    manufacturer: "RockShox",
    model: "ZEB Ultimate",
    variant: "170mm 29 Charger 3.1",
    modelYear: 2024,
    weightG: 2350,
    attributes: [
      attr("travel_mm", { num: 170, unit: "mm" }),
      attr("steerer_type", { enum: "tapered_1.5" }),
      attr("steerer_clamp_mm", { num: 28.6, unit: "mm" }),
      attr("crown_race_mm", { num: 40, unit: "mm" }),
      attr("axle_front", { enum: "15x110_boost" }),
      attr("brake_mount", { enum: "post_mount" }),
      attr("max_rotor_mm", { num: 220, unit: "mm" }),
      attr("wheel_size", { enum: "29" }),
      attr("offset_mm", { num: 44, unit: "mm" }),
    ],
    adjusters: forkAdjusters(20, 15, 5),
    torqueSpecs: [],
    source: "manufacturer_doc",
    sourceUrl: "https://www.sram.com/en/rockshox",
    verifiedAt: VERIFIED,
    verifiedBy: "AetherRide Editorial",
    safetyCritical: true,
  },
  {
    id: "cm-ohlins-rxf38-170",
    slot: "fork",
    manufacturer: "Öhlins",
    model: "RXF 38 m.2",
    variant: "170mm 29",
    modelYear: 2024,
    attributes: [
      attr("travel_mm", { num: 170, unit: "mm" }),
      attr("steerer_type", { enum: "tapered_1.5" }),
      attr("axle_front", { enum: "15x110_boost" }),
      attr("brake_mount", { enum: "post_mount" }),
      attr("max_rotor_mm", { num: 220, unit: "mm" }),
      attr("wheel_size", { enum: "29" }),
      attr("offset_mm", { num: 44, unit: "mm" }),
    ],
    adjusters: forkAdjusters(),
    torqueSpecs: [],
    source: "manufacturer_doc",
    sourceUrl: "https://www.ohlins.com/",
    verifiedAt: VERIFIED,
    verifiedBy: "AetherRide Editorial",
    safetyCritical: true,
  },

  // —— Dämpfer ——
  {
    id: "cm-fox-float-x-20565",
    slot: "rear_shock",
    manufacturer: "Fox",
    model: "FLOAT X",
    variant: "205×65 Trunnion",
    modelYear: 2024,
    attributes: [
      attr("eye_to_eye_mm", { num: 205, unit: "mm" }),
      attr("stroke_mm", { num: 65, unit: "mm" }),
      attr("mount_type", { enum: "trunnion" }),
    ],
    adjusters: [
      {
        key: "air_pressure_psi",
        label: "Luftdruck",
        unit: "psi",
        min: 100,
        max: 350,
        step: 1,
      },
      {
        key: "sag_pct",
        label: "SAG",
        unit: "%",
        min: 25,
        max: 35,
        step: 1,
      },
      {
        key: "rebound",
        label: "Zugstufe",
        unit: "clicks",
        totalClicks: 16,
        reference: "from_closed",
        min: 0,
        max: 16,
        step: 1,
      },
      {
        key: "lsc",
        label: "LSC",
        unit: "clicks",
        totalClicks: 16,
        reference: "from_closed",
        min: 0,
        max: 16,
        step: 1,
      },
    ],
    torqueSpecs: [],
    source: "manufacturer_doc",
    sourceUrl: "https://www.ridefox.com/",
    verifiedAt: VERIFIED,
    verifiedBy: "AetherRide Editorial",
    safetyCritical: true,
  },
  {
    id: "cm-fox-float-x-21055",
    slot: "rear_shock",
    manufacturer: "Fox",
    model: "FLOAT X",
    variant: "210×55 Trunnion",
    modelYear: 2024,
    attributes: [
      attr("eye_to_eye_mm", { num: 210, unit: "mm" }),
      attr("stroke_mm", { num: 55, unit: "mm" }),
      attr("mount_type", { enum: "trunnion" }),
    ],
    adjusters: [
      {
        key: "air_pressure_psi",
        label: "Luftdruck",
        unit: "psi",
        min: 100,
        max: 350,
        step: 1,
      },
      {
        key: "sag_pct",
        label: "SAG",
        unit: "%",
        min: 25,
        max: 35,
        step: 1,
      },
      {
        key: "rebound",
        label: "Zugstufe",
        unit: "clicks",
        totalClicks: 16,
        reference: "from_closed",
        min: 0,
        max: 16,
        step: 1,
      },
      {
        key: "lsc",
        label: "LSC",
        unit: "clicks",
        totalClicks: 16,
        reference: "from_closed",
        min: 0,
        max: 16,
        step: 1,
      },
    ],
    torqueSpecs: [],
    source: "manufacturer_doc",
    sourceUrl: "https://www.ridefox.com/",
    verifiedAt: VERIFIED,
    verifiedBy: "AetherRide Editorial",
    safetyCritical: true,
  },
  {
    id: "cm-fox-float-x2-23065",
    slot: "rear_shock",
    manufacturer: "Fox",
    model: "Float X2 Factory",
    variant: "230×65 Trunnion",
    modelYear: 2024,
    attributes: [
      attr("eye_to_eye_mm", { num: 230, unit: "mm" }),
      attr("stroke_mm", { num: 65, unit: "mm" }),
      attr("mount_type", { enum: "trunnion" }),
    ],
    adjusters: [
      {
        key: "air_pressure_psi",
        label: "Luftdruck",
        unit: "psi",
        min: 100,
        max: 350,
        step: 5,
      },
      {
        key: "sag_pct",
        label: "SAG",
        unit: "%",
        min: 20,
        max: 40,
        step: 1,
      },
      {
        key: "rebound",
        label: "Zugstufe",
        unit: "clicks",
        totalClicks: 16,
        reference: "from_closed",
        min: 0,
        max: 16,
        step: 1,
      },
      {
        key: "lsc",
        label: "LSC",
        unit: "clicks",
        totalClicks: 16,
        reference: "from_closed",
        min: 0,
        max: 16,
        step: 1,
      },
      {
        key: "hsc",
        label: "HSC",
        unit: "clicks",
        totalClicks: 8,
        reference: "from_closed",
        min: 0,
        max: 8,
        step: 1,
      },
    ],
    torqueSpecs: [],
    source: "manufacturer_doc",
    sourceUrl: "https://www.ridefox.com/",
    verifiedAt: VERIFIED,
    verifiedBy: "AetherRide Editorial",
    safetyCritical: true,
  },
  {
    id: "cm-rockshox-vivid-20565",
    slot: "rear_shock",
    manufacturer: "RockShox",
    model: "Vivid Ultimate",
    variant: "205×65 Trunnion",
    modelYear: 2024,
    attributes: [
      attr("eye_to_eye_mm", { num: 205, unit: "mm" }),
      attr("stroke_mm", { num: 65, unit: "mm" }),
      attr("mount_type", { enum: "trunnion" }),
    ],
    adjusters: [
      {
        key: "air_pressure_psi",
        label: "Luftdruck",
        unit: "psi",
        min: 100,
        max: 350,
        step: 1,
      },
      {
        key: "sag_pct",
        label: "SAG",
        unit: "%",
        min: 25,
        max: 35,
        step: 1,
      },
      {
        key: "rebound",
        label: "Zugstufe",
        unit: "clicks",
        totalClicks: 20,
        reference: "from_closed",
        min: 0,
        max: 20,
        step: 1,
      },
    ],
    torqueSpecs: [],
    source: "manufacturer_doc",
    sourceUrl: "https://www.sram.com/en/rockshox",
    verifiedAt: VERIFIED,
    verifiedBy: "AetherRide Editorial",
    safetyCritical: true,
  },
  {
    id: "cm-rockshox-vivid-23065",
    slot: "rear_shock",
    manufacturer: "RockShox",
    model: "Vivid Ultimate",
    variant: "230×65 Trunnion",
    modelYear: 2024,
    attributes: [
      attr("eye_to_eye_mm", { num: 230, unit: "mm" }),
      attr("stroke_mm", { num: 65, unit: "mm" }),
      attr("mount_type", { enum: "trunnion" }),
    ],
    adjusters: [
      {
        key: "air_pressure_psi",
        label: "Luftdruck",
        unit: "psi",
        min: 100,
        max: 350,
        step: 1,
      },
      {
        key: "sag_pct",
        label: "SAG",
        unit: "%",
        min: 25,
        max: 35,
        step: 1,
      },
      {
        key: "rebound",
        label: "Zugstufe",
        unit: "clicks",
        totalClicks: 20,
        reference: "from_closed",
        min: 0,
        max: 20,
        step: 1,
      },
    ],
    torqueSpecs: [],
    source: "manufacturer_doc",
    sourceUrl: "https://www.sram.com/en/rockshox",
    verifiedAt: VERIFIED,
    verifiedBy: "AetherRide Editorial",
    safetyCritical: true,
  },

  // —— Dropper 30,9 mm (Canyon/Cube) ——
  {
    id: "cm-oneup-v3-dropper-30-9",
    slot: "seatpost",
    manufacturer: "OneUp",
    model: "V3 Dropper",
    variant: "30.9 × 180mm",
    attributes: [
      attr("seatpost_diameter_mm", { num: 30.9, unit: "mm" }),
      attr("min_insertion_mm", { num: 140, unit: "mm" }),
      attr("dropper_travel_mm", { num: 180, unit: "mm" }),
    ],
    adjusters: [],
    torqueSpecs: [
      {
        fastener: "Sattelklemme",
        nm: 6,
        sourceUrl: "https://oneupcomponents.com/",
        sourceLabel: "OneUp Manual",
      },
    ],
    source: "manufacturer_doc",
    sourceUrl: "https://oneupcomponents.com/",
    verifiedAt: VERIFIED,
    verifiedBy: "AetherRide Editorial",
    safetyCritical: true,
  },

  // —— Rahmen DACH-Marken ——
  frameEnduro({
    id: "cm-yt-capra-frame",
    manufacturer: "YT Industries",
    model: "Capra",
    variant: "MX Uncaged 9",
    year: 2024,
    shockEye: 205,
    shockStroke: 65,
    shockMount: "trunnion",
    seatpostMm: 31.6,
    url: "https://www.yt-industries.com/",
  }),
  frameEnduro({
    id: "cm-propain-tyee-frame",
    manufacturer: "Propain",
    model: "Tyee",
    variant: "AL",
    year: 2024,
    shockEye: 230,
    shockStroke: 65,
    shockMount: "trunnion",
    seatpostMm: 31.6,
    url: "https://www.propain-bikes.com/",
  }),
  frameEnduro({
    id: "cm-canyon-spectral-cf-frame",
    manufacturer: "Canyon",
    model: "Spectral CF",
    variant: "CF 8",
    year: 2024,
    shockEye: 210,
    shockStroke: 55,
    shockMount: "trunnion",
    seatpostMm: 30.9,
    url: "https://www.canyon.com/",
  }),
  frameEnduro({
    id: "cm-cube-stereo-one44-frame",
    manufacturer: "Cube",
    model: "Stereo ONE44",
    variant: "C:62",
    year: 2024,
    shockEye: 210,
    shockStroke: 55,
    shockMount: "trunnion",
    seatpostMm: 30.9,
    url: "https://www.cube.eu/",
  }),
  frameEnduro({
    id: "cm-rose-root-miller-frame",
    manufacturer: "Rose",
    model: "Root Miller 3",
    variant: "Enduro",
    year: 2024,
    shockEye: 205,
    shockStroke: 65,
    shockMount: "trunnion",
    seatpostMm: 31.6,
    url: "https://www.rosebikes.de/",
  }),
  frameEnduro({
    id: "cm-specialized-enduro-frame",
    manufacturer: "Specialized",
    model: "Enduro",
    variant: "Comp",
    year: 2024,
    shockEye: 205,
    shockStroke: 65,
    shockMount: "trunnion",
    seatpostMm: 34.9,
    url: "https://www.specialized.com/",
  }),
  frameEnduro({
    id: "cm-trek-slash-frame",
    manufacturer: "Trek",
    model: "Slash",
    variant: "8",
    year: 2024,
    shockEye: 230,
    shockStroke: 65,
    shockMount: "trunnion",
    seatpostMm: 34.9,
    url: "https://www.trekbikes.com/",
  }),
  frameEnduro({
    id: "cm-cube-stereo-hybrid-frame",
    manufacturer: "Cube",
    model: "Stereo Hybrid 160",
    variant: "HPC Race",
    year: 2024,
    shockEye: 230,
    shockStroke: 65,
    shockMount: "trunnion",
    seatpostMm: 30.9,
    url: "https://www.cube.eu/",
    motor: "bosch_smart_system",
  }),

  // —— Bremsen DACH-üblich ——
  {
    id: "cm-magura-mt7-front",
    slot: "brake_front",
    manufacturer: "Magura",
    model: "MT7",
    variant: "HC 1-Finger",
    attributes: [
      attr("brake_mount", { enum: "post_mount" }),
      attr("rotor_mount", { enum: "6_bolt" }),
    ],
    adjusters: [],
    torqueSpecs: [],
    source: "manufacturer_doc",
    sourceUrl: "https://www.magura.com/",
    verifiedAt: VERIFIED,
    verifiedBy: "AetherRide Editorial",
    safetyCritical: true,
  },
  {
    id: "cm-magura-mt7-rear",
    slot: "brake_rear",
    manufacturer: "Magura",
    model: "MT7",
    variant: "HC 1-Finger",
    attributes: [
      attr("brake_mount", { enum: "post_mount" }),
      attr("rotor_mount", { enum: "6_bolt" }),
    ],
    adjusters: [],
    torqueSpecs: [],
    source: "manufacturer_doc",
    sourceUrl: "https://www.magura.com/",
    verifiedAt: VERIFIED,
    verifiedBy: "AetherRide Editorial",
    safetyCritical: true,
  },
  {
    id: "cm-shimano-xt-m8120-front",
    slot: "brake_front",
    manufacturer: "Shimano",
    model: "XT M8120",
    variant: "4-Kolben",
    attributes: [
      attr("brake_mount", { enum: "post_mount" }),
      attr("rotor_mount", { enum: "center_lock" }),
    ],
    adjusters: [],
    torqueSpecs: [],
    source: "manufacturer_doc",
    sourceUrl: "https://bike.shimano.com/",
    verifiedAt: VERIFIED,
    verifiedBy: "AetherRide Editorial",
    safetyCritical: true,
  },
  {
    id: "cm-shimano-xt-m8120-rear",
    slot: "brake_rear",
    manufacturer: "Shimano",
    model: "XT M8120",
    variant: "4-Kolben",
    attributes: [
      attr("brake_mount", { enum: "post_mount" }),
      attr("rotor_mount", { enum: "center_lock" }),
    ],
    adjusters: [],
    torqueSpecs: [],
    source: "manufacturer_doc",
    sourceUrl: "https://bike.shimano.com/",
    verifiedAt: VERIFIED,
    verifiedBy: "AetherRide Editorial",
    safetyCritical: true,
  },
  {
    id: "cm-shimano-rt86-203-front",
    slot: "rotor_front",
    manufacturer: "Shimano",
    model: "RT86 Ice-Tech",
    variant: "203mm Centerlock",
    attributes: [
      attr("rotor_diameter_mm", { num: 203, unit: "mm" }),
      attr("rotor_mount", { enum: "center_lock" }),
    ],
    adjusters: [],
    torqueSpecs: [],
    source: "manufacturer_doc",
    sourceUrl: "https://bike.shimano.com/",
    verifiedAt: VERIFIED,
    verifiedBy: "AetherRide Editorial",
    safetyCritical: true,
  },
  {
    id: "cm-shimano-rt86-180-rear",
    slot: "rotor_rear",
    manufacturer: "Shimano",
    model: "RT86 Ice-Tech",
    variant: "180mm Centerlock",
    attributes: [
      attr("rotor_diameter_mm", { num: 180, unit: "mm" }),
      attr("rotor_mount", { enum: "center_lock" }),
    ],
    adjusters: [],
    torqueSpecs: [],
    source: "manufacturer_doc",
    sourceUrl: "https://bike.shimano.com/",
    verifiedAt: VERIFIED,
    verifiedBy: "AetherRide Editorial",
    safetyCritical: true,
  },

  // —— Reifen DACH-Enduro ——
  {
    id: "cm-maxxis-minion-dhf-29-25",
    slot: "tire_front",
    manufacturer: "Maxxis",
    model: "Minion DHF",
    variant: "29×2.5 WT EXO+",
    attributes: [
      attr("tire_width_mm", { num: 63.5, unit: "mm" }),
      attr("wheel_size", { enum: "29" }),
      attr("etrto", { text: "63-622" }),
      attr("tubeless_ready", { enum: "yes" }),
    ],
    adjusters: [
      {
        key: "pressure_psi",
        label: "Luftdruck",
        unit: "psi",
        min: 15,
        max: 35,
        step: 0.5,
      },
    ],
    torqueSpecs: [],
    source: "manufacturer_doc",
    sourceUrl: "https://www.maxxis.com/",
    verifiedAt: VERIFIED,
    verifiedBy: "AetherRide Editorial",
    safetyCritical: false,
  },
  {
    id: "cm-continental-kryptotal-f-29",
    slot: "tire_front",
    manufacturer: "Continental",
    model: "Kryptotal-F",
    variant: "29×2.4 Endurance Soft",
    attributes: [
      attr("tire_width_mm", { num: 60, unit: "mm" }),
      attr("wheel_size", { enum: "29" }),
      attr("etrto", { text: "60-622" }),
      attr("tubeless_ready", { enum: "yes" }),
    ],
    adjusters: [
      {
        key: "pressure_psi",
        label: "Luftdruck",
        unit: "psi",
        min: 15,
        max: 35,
        step: 0.5,
      },
    ],
    torqueSpecs: [],
    source: "manufacturer_doc",
    sourceUrl: "https://www.continental-tires.com/",
    verifiedAt: VERIFIED,
    verifiedBy: "AetherRide Editorial",
    safetyCritical: false,
  },
  {
    id: "cm-continental-kryptotal-r-29",
    slot: "tire_rear",
    manufacturer: "Continental",
    model: "Kryptotal-R",
    variant: "29×2.4 Endurance Soft",
    attributes: [
      attr("tire_width_mm", { num: 60, unit: "mm" }),
      attr("wheel_size", { enum: "29" }),
      attr("etrto", { text: "60-622" }),
      attr("tubeless_ready", { enum: "yes" }),
    ],
    adjusters: [
      {
        key: "pressure_psi",
        label: "Luftdruck",
        unit: "psi",
        min: 18,
        max: 40,
        step: 0.5,
      },
    ],
    torqueSpecs: [],
    source: "manufacturer_doc",
    sourceUrl: "https://www.continental-tires.com/",
    verifiedAt: VERIFIED,
    verifiedBy: "AetherRide Editorial",
    safetyCritical: false,
  },

  // —— Antrieb Shimano ——
  {
    id: "cm-shimano-xt-rd-m8100",
    slot: "rear_derailleur",
    manufacturer: "Shimano",
    model: "XT M8100",
    variant: "12-speed SGS",
    attributes: [
      attr("speed", { num: 12 }),
      attr("freehub_standard", { enum: "MicroSpline" }),
    ],
    adjusters: [],
    torqueSpecs: [],
    source: "manufacturer_doc",
    sourceUrl: "https://bike.shimano.com/",
    verifiedAt: VERIFIED,
    verifiedBy: "AetherRide Editorial",
    safetyCritical: false,
  },
  {
    id: "cm-shimano-xt-shifter-m8100",
    slot: "shifter",
    manufacturer: "Shimano",
    model: "XT M8100",
    variant: "I-Spec EV",
    attributes: [attr("speed", { num: 12 })],
    adjusters: [],
    torqueSpecs: [],
    source: "manufacturer_doc",
    sourceUrl: "https://bike.shimano.com/",
    verifiedAt: VERIFIED,
    verifiedBy: "AetherRide Editorial",
    safetyCritical: false,
  },
  {
    id: "cm-shimano-xt-crank-m8120",
    slot: "crankset",
    manufacturer: "Shimano",
    model: "XT M8120",
    variant: "170mm",
    attributes: [
      attr("crank_axle", { enum: "24mm" }),
      attr("chainring_bcd", { enum: "direct_mount" }),
    ],
    adjusters: [],
    torqueSpecs: [],
    source: "manufacturer_doc",
    sourceUrl: "https://bike.shimano.com/",
    verifiedAt: VERIFIED,
    verifiedBy: "AetherRide Editorial",
    safetyCritical: false,
  },
  {
    id: "cm-shimano-bb-mt800",
    slot: "bottom_bracket",
    manufacturer: "Shimano",
    model: "BB-MT800",
    variant: "BSA 73",
    attributes: [
      attr("bb_standard", { enum: "BSA73" }),
      attr("crank_axle", { enum: "24mm" }),
    ],
    adjusters: [],
    torqueSpecs: [],
    source: "manufacturer_doc",
    sourceUrl: "https://bike.shimano.com/",
    verifiedAt: VERIFIED,
    verifiedBy: "AetherRide Editorial",
    safetyCritical: false,
  },
  {
    id: "cm-shimano-xt-chainring-32",
    slot: "chainring",
    manufacturer: "Shimano",
    model: "XT",
    variant: "32T Direct Mount",
    attributes: [
      attr("teeth", { num: 32 }),
      attr("chainring_bcd", { enum: "direct_mount" }),
    ],
    adjusters: [],
    torqueSpecs: [],
    source: "manufacturer_doc",
    sourceUrl: "https://bike.shimano.com/",
    verifiedAt: VERIFIED,
    verifiedBy: "AetherRide Editorial",
    safetyCritical: false,
  },
  {
    id: "cm-shimano-cn-m8100",
    slot: "chain",
    manufacturer: "Shimano",
    model: "CN-M8100",
    variant: "12-speed",
    attributes: [attr("speed", { num: 12 })],
    adjusters: [],
    torqueSpecs: [],
    source: "manufacturer_doc",
    sourceUrl: "https://bike.shimano.com/",
    verifiedAt: VERIFIED,
    verifiedBy: "AetherRide Editorial",
    safetyCritical: false,
  },

  // —— Naben Centerlock ——
  {
    id: "cm-dt-350-boost-front-cl",
    slot: "front_hub",
    manufacturer: "DT Swiss",
    model: "350",
    variant: "15×110 Boost Centerlock",
    attributes: [
      attr("axle_front", { enum: "15x110_boost" }),
      attr("rotor_mount", { enum: "center_lock" }),
    ],
    adjusters: [],
    torqueSpecs: [],
    source: "manufacturer_doc",
    sourceUrl: "https://www.dtswiss.com/",
    verifiedAt: VERIFIED,
    verifiedBy: "AetherRide Editorial",
    safetyCritical: true,
  },
  {
    id: "cm-dt-350-boost-rear-ms-cl",
    slot: "rear_hub",
    manufacturer: "DT Swiss",
    model: "350",
    variant: "12×148 Boost Micro Spline Centerlock",
    attributes: [
      attr("rear_spacing", { enum: "148x12_boost" }),
      attr("axle_rear", { enum: "12x148_boost" }),
      attr("freehub_standard", { enum: "MicroSpline" }),
      attr("rotor_mount", { enum: "center_lock" }),
    ],
    adjusters: [],
    torqueSpecs: [],
    source: "manufacturer_doc",
    sourceUrl: "https://www.dtswiss.com/",
    verifiedAt: VERIFIED,
    verifiedBy: "AetherRide Editorial",
    safetyCritical: true,
  },
];
